### ISSUE TITLE
All the Colabs with adapter training fail due to tensors being on different devices

### ISSUE THREAD

**Issue by sbassam** [Adapter-Hub/adapter-transformers#100]
Hi,

I'm trying to train an adapter and I'm getting the following error:
`RuntimeError: Tensor for 'out' is on CPU, Tensor for argument #1 'self' is on CPU, but expected them to be on GPU (while checking arguments for addmm)`
to reproduce this, you can just run any of the colabs provided in the tutorials. For example, running the cells in [this](https://colab.research.google.com/github/Adapter-Hub/website/blob/master/app/static/notebooks/Adapter_Quickstart_Training.ipynb#scrollTo=tXHpbKVwwiuz) one, the training line (`trainer.train()`) throws this error.

**Comment by calpt** [comment]
Hi @sbassam,

Thank you very much for reporting this, this is indeed a bug in the latest version of the master branch in this repo. Until fixed, please switch to the latest stable version from PyPI where this bug shouldn't be present. Install using:
```
pip install -U adapter-transformers
```
(You may have to `pip uninstall` the current version of adapter-transformers first.)
