### ISSUE TITLE
Is the initialization function redundant here?

### ISSUE THREAD

**Issue by li3cmz** [Adapter-Hub/adapter-transformers#108]
https://github.com/Adapter-Hub/adapter-transformers/blob/34a0ccacdac96d7ce4402b20da1fa6cd3ce99010/src/transformers/modeling_bert.py#L771

The function will add an adapter to the encoder by default. However, according to the [doc](https://docs.adapterhub.ml/adapters.html), we could add an adapter through the `add_adapter()` method. Is the initialization function redundant here?

**Comment by calpt** [comment]
No, it's not directly redundant (although sharing some functionality):

`_init_adapter_modules()` is an internal method which should be called by every model class implementing adapters (and should not be called by the user). It makes sure that all adapters and adapter fusion layers defined in the model config at initialization time are correctly added during the creation of the model. This e.g. is the case when you load a full model including adapters from the file system with `model_class.from_pretrained("model_folder")`. The method will do nothing in case there are no adapters in the loaded model.

`add_adapter()` is the method a user should call to add a new adapter module to an existing model. It has some additional checks and options not part of the internal logic.

Hope this helps!
