### ISSUE TITLE
number of iterations for all datasets in adapter fusion 

### ISSUE THREAD

**Issue by rabeehk** [Adapter-Hub/adapter-transformers#109]
Hi
could you clarify the number of training iterations? I could not find it in the paper
thanks

**Comment by JoPfeiff** [comment]
We have updated the paper.
https://arxiv.org/abs/2005.00247 
We again train with early stopping.

Please also check the outlook section. We have recommendations how AdapterFusion performs better.
i.e. Dropping the adapter in the last layer (e.g. 12th layer for BERT-base and RoBERTa-base) usually improves performance considerably!
