### ISSUE TITLE
questions on reproducing AdapterFusion paper's results 

### ISSUE THREAD

**Issue by rabeehk** [Adapter-Hub/adapter-transformers#112]
Hi there,

I need to reproduce the adapter fusion paper's results in table 1, I have a couple of questions:

1) I was wondering if you could share with me possible scripts to have this table reproduced.
2) In the paper this is mentioned that you report on the dev set, then do you also tune the parameters on the dev set? could you specify how you tune the parameters? 
3) could you assist me in getting the "Argument" and "CB" datasets, the way you processed it, did you download these two datasets from huggingface datasets? If yes, I could not find the names, could you share their corresponding names in datasets library. 
4) winogrande has multiple datasets of various size, could you specify which dataset of winograde is reported in the paper?

Thank you.

**Comment by JoPfeiff** [comment]
1) the scripts are no longer compatible with the current version of the adapter hub. We are planning to provide some evaluation scripts soon.
2) we only select the best epoch on the dev set, all other hyperparameters are fixed for all models.
3) CB is available in superglue. Argument needs to be processed as described in the original paper, unfortunately we are not allowed to distribute it.
4) largest version
