### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by uunal** [Adapter-Hub/adapter-transformers#114]
`!pip install git+https://github.com/adapter-hub/adapter-transformers.git -qq`

Message:  `ERROR: transformers 4.1.1 has requirement tokenizers==0.9.4, but you'll have tokenizers 0.9.3 which is incompatible.`

Probably Transformers library got an update and causes the problem.

**Comment by calpt** [comment]
Yes, this seems to be caused by a parallel transformers installation. The current version of adapter-transformers is based on transformers v3.5.1. Please try to uninstall the newer transformers version and re-install only adapter-transformers.
