### ISSUE TITLE
Early stopping during adapter training?

### ISSUE THREAD

**Issue by fvancesco** [Adapter-Hub/adapter-transformers#115]
Hello, 

is there a way to terminate early the training if the validation loss is not improving?

Thanks

**Comment by calpt** [comment]
Sorry for the very late answer. This is possible with the early stopping callback of HuggingFace's `Trainer` class: https://github.com/Adapter-Hub/adapter-transformers/blob/fc62058af8dd283c98c6a9ff59201b8f6f23394f/src/transformers/trainer_callback.py#L505

E.g. applied here: https://github.com/Adapter-Hub/adapter-transformers/blob/fc62058af8dd283c98c6a9ff59201b8f6f23394f/examples/seq2seq/run_summarization.py#L590-L592
