### ISSUE TITLE
TypeError: non-default argument 'non_linearity' follows default argument

### ISSUE THREAD

**Issue by mandel-drink** [Adapter-Hub/adapter-transformers#118]
Hi all,

I am new to the adapter-transformers. I checked the examples folder and tests folders in repo to make a quick try. When setting up the dataset, I took the code in previous-mentioned folders and run, but I got a file-not-found-error as the following. Could you please shed some lights on why I got the error and how do I remove it? Thank you.

FileNotFoundError: [Errno 2] No such file or directory: './tests/fixtures/tests_samples/MRPC/cached_train_BertTokenizer_128_mrpc.lock'.

`    # setup dataset

    data_args = GlueDataTrainingArguments(
        task_name="mrpc", data_dir="./tests/fixtures/tests_samples/MRPC", overwrite_cache=True
    )
    train_dataset = GlueDataset(data_args, tokenizer=tokenizer, mode="train")
    training_args = TrainingArguments(
        output_dir="./tests", do_train=True, learning_rate=0.1, max_steps=5, no_cuda=True
    )`

## Environment info

- `transformers` version: 1.1.1
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7.0 (True)

## Details

`    # setup dataset

    data_args = GlueDataTrainingArguments(
        task_name="mrpc", data_dir="./tests/fixtures/tests_samples/MRPC", overwrite_cache=True
    )
    train_dataset = GlueDataset(data_args, tokenizer=tokenizer, mode="train")
    training_args = TrainingArguments(
        output_dir="./tests", do_train=True, learning_rate=0.1, max_steps=5, no_cuda=True
    )`

FileNotFoundError: [Errno 2] No such file or directory: './tests/fixtures/tests_samples/MRPC/cached_train_BertTokenizer_128_mrpc.lock'

**Comment by mandel-drink** [comment]
Hi all,

The issue has been solved by using get_tests_dir() from transformers.testing_utils. :)

I have another question about a warning I received in terminal: "There are adapters available but none are passed to model.forward". Does it mean that I didn't use the available adapters I loaded? Could you please check the following code? I thought I did use the available adapters in forward propagation by doing model.add_adapter(...) or AutoModelWithHeads.from_pretrained(config=AdapterConfig.load(...)) before training the model?

The code I used is as follows:

`    config_name, model_name = "pfeiffer", "bert-base-uncased"

    config = AdapterConfig.load(config_name, non_linearity='relu', reduction_factor=16)

    model = AutoModelWithHeads.from_pretrained(
        model_name,
        config=config,
    )

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    # setup dataset
    data_args = GlueDataTrainingArguments(
        task_name="mrpc", data_dir=f"{get_tests_dir()}/fixtures/tests_samples/MRPC", overwrite_cache=True
    )
    train_dataset = GlueDataset(data_args, tokenizer=tokenizer, mode="train")
    training_args = TrainingArguments(
        output_dir="./tests", do_train=True, learning_rate=0.1, max_steps=5, no_cuda=True
    )

    model.add_classification_head(data_args.task_name)

    # add a new adapter
    model.add_adapter(
        data_args.task_name,
        AdapterType.text_task,
        config=config_name
    )

    # evaluate
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
    )
    trainer.train()`

**Comment by calpt** [comment]
Hi @mandel-drink,

seems like you figured out most of the issues yourself. Regarding the last question:

> I have another question about a warning I received in terminal: "Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModelWithHeads: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']".

This is perfectly normal and expected. You're loading a checkpoint from HuggingFace which was pre-trained on language modeling and therefore has a language modeling prediction head. Since you're training it on sequence classification, the weights of the language modeling head are not used and thus not loaded from the checkpoint.

(Also see https://github.com/huggingface/transformers/issues/5421#issuecomment-652582854 in the HF transformers repo.)

**Comment by mandel-drink** [comment]
Hey @calpt,

Thank you very much for the answer. It makes pretty much sense. :)

May I ask another question about an error I got, when I wanted to make the import to take from my local instead of from the repo. The reason why I raised this question is because when I use this method on other repo packages and they work without errors. Could you please advise it if you have any clues? Thank you.

I wrote the following command in the folder of adapter-transformers, which I cloned from the repo.
`python setup.py install develop`

So when I wrote `pip3 list`, adapter-transformers has version 1.1.1 and the location is at my local device, rather than empty. However, when I wrote `from transformers import AdapterConfig` in python file, I got below error.

`
from transformers import (
File "/adapter/src/transformers/__init__.py", line 32, in <module>
    from .configuration_auto import ALL_PRETRAINED_CONFIG_ARCHIVE_MAP, CONFIG_MAPPING, AutoConfig
  File "/adapter/src/transformers/configuration_auto.py", line 22, in <module>
    from .configuration_bert import BERT_PRETRAINED_CONFIG_ARCHIVE_MAP, BertConfig
  File "/adapter/src/transformers/configuration_bert.py", line 19, in <module>
    from .adapter_config import ModelAdaptersConfig
  File "/adapter/src/transformers/adapter_config.py", line 125, in <module>
    class PfeifferConfig(AdapterConfig):
  File "/lib/python3.6/site-packages/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/lib/python3.6/site-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/lib/python3.6/site-packages/dataclasses.py", line 871, in _process_class
    else 'self',
  File "/lib/python3.6/site-packages/dataclasses.py", line 460, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'non_linearity' follows default argument
`
