### ISSUE TITLE
Using different reduction factor for a certain layer

### ISSUE THREAD

**Issue by seungwon1** [Adapter-Hub/adapter-transformers#124]
## Environment info
- `adapter-transformers` version: 1.1.0
- Platform: ubuntu20.04
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.1. (RTX 3090)

## Details
Hello.

Can I use different reduction factor for a certain layer? For instance, I would like to increase/decrease the number of parameters in the top/lower layers.

**Comment by calpt** [comment]
Hi @seungwon1,

We currently don't have a simple way to do this. You could add different adapters with different reduction factors to certain layers only (by using `leave_out` in the config to specify the layers for which _no_ adapter should be added) and then set all adapters as active.

But I think we could add the option to specify a list of reduction factors in the adapter config, matching the number of layers in the model. Would that fit your use case?

**Comment by seungwon1** [comment]
Hi, @calpt.
Thank you for the reply. That'll do.

**Comment by aabid0193** [comment]
Is this still in progress?
