### ISSUE TITLE
Training task-specific adapter and adapter fusion layer at the same time

### ISSUE THREAD

**Issue by seungwon1** [Adapter-Hub/adapter-transformers#126]
## Environment info

     
- `adapter-transformers` version: 1.1.0
- Platform: ubuntu20.04
- Python version:3.8.5
- PyTorch version (GPU?):1.7.1. (RTX 3090)

## Details

Hi, is it possible to train the task-specific adapter module and the adapter fusion layer at the same time?

E.g., 
model.load_adapter(each_adapter)
model.add_fusion(ADAPTER_SETUP[0], "dynamic")
model.train_fusion(ADAPTER_SETUP)

When I loaded fine-tuned adapter and add the fusion layer, the weights of the task-specific adapter are frozen during the training.

**Comment by calpt** [comment]
Yes, that should be possible. `train_adapter()` and `train_fusion()` both call `enable_adapters()` on the encoder component of the model to enable adapters/ adapter fusion. `train_fusion()` will freeze task adapters, but you can re-enable them afterwards with:
```
model.encoder.enable_adapters(ADAPTER_SETUP[0], True, True)
```
The second argument enables the adapters part of the fusion setup, the third enables the fusion layer itself.

**Comment by seungwon1** [comment]
Hi, @calpt 
Thanks for the instructions.
