### ISSUE TITLE
Add T5 support

### ISSUE THREAD

**Issue by calpt** [Adapter-Hub/adapter-transformers#127]
Add adapters to the T5 model.

**Comment by calpt** [comment]
@AmirAktify Apparently, I'm not able to assign someone who hasn't commented on an issue 😄. Just noting here for other's that you're planning to work on this.

**Comment by AmirAktify** [comment]
Yes! Just started on this today. I'll circle back on the weekend with my progress.

**Comment by calpt** [comment]
Hey @AmirAktify, just wanted to ask if you're still working on this and/ or need help. In case you currently don't have the capacity/ motivation to continue on this, we'd be happy to take over.

**Comment by AmirAktify** [comment]
Hi @calpt. Give me 24 hours to see how much further I can get with my branch, and then let's resync on where the code is at?  I certainly don't want to block this either.

**Comment by calpt** [comment]
No problem, take your time. (By the way, the newest version is now on the master branch, so we'd sync with that in the end)

**Comment by AmirAktify** [comment]
Is this out of date in the documentation?

Where in [adding adapters docs](https://github.com/Adapter-Hub/adapter-transformers/blob/master/adding_adapters_to_a_model.md) it says: 

```Add a new adapter_<model_type>.py module for your architecture (or reuse an existing if possible).```

It should instead be add a `src/transformers/adapters/models/<model_type>.py`, I assume? And then modify `src/transformers/models/modeling_<model_type>.py` appropriately.

 I'm writing code with that assumption in mind.

**Comment by calpt** [comment]
Yes, your assumption is right. Thanks for the hint, I'll update the documentation.

**Comment by AmirAktify** [comment]
I've made some headway on this, mostly adapting the bart.py setup. It's going faster now that I've gronked the basics. 

t5 uses a single T5Stack class for both the encoder and decoder, which makes it a little trickier to add invertible adapters to only the encoder, and not the decoder. (as compared to bart which has a separate BartEncoder and BartDecoder class). Does using the .is_decoder in the config to manage this behavior seem reasonable?

**Comment by AmirAktify** [comment]
Yes, using the `.is_decoder` made it pretty easy for T5Stack to switch between using the `invertible adapters` for whether its the encoder or decoder. I was able to do something similar for T5Block, to enable it to include `CrossAttentionAdapters` in only the `decoder` and not the `encoder`.  

In theory it should be working now. Now I'll be doing some testing / training / adding adapters to see whether I broke it terribly or not.

I'll be working with Glue first, if there's another benchmark you'd prefer I try first, please let me know.

**Comment by calpt** [comment]
Sounds great! GLUE is perfectly fine as the first benchmark for validation. Feel free to open a draft PR at any time even if you're not sure everything works 100% yet :)

**Comment by wkddydpf** [comment]
Hi, how is the progress going for providing T5 support? Thank you!

**Comment by AmirAktify** [comment]
I have an MR I'm working on here: https://github.com/Adapter-Hub/adapter-transformers/pull/182. Doing some testing and debugging over memorial day weekend.

**Comment by AmirAktify** [comment]
So, while working on this, I realized there's this annoying thing that `T5` does where the encoder and decoder configs are set by `deepcopy` and modification of the base model's config, instead of by reference as you might see in `bart`.  Since these configs are used extensively to track adding and removing adapters, it means I have to explicitly recouple the configs at encoder / decoder and base model level frequently. 

Any suggestions if there's a cleaner way to do this without factoring out huggingface's deep copy and separation of configs?

**Comment by AmirAktify** [comment]
I'm just refactoring the `huggingface` code for T5Stack very slightly to make this work for now.

**Comment by AmirAktify** [comment]
For the above mentioned `deepcopy` problem, I worked around it with some software engineering copying a couple of variables around.

I had many many embarrassing major bugs in my branch, fixed most of those locally on my system last week. I'll push my updates after cleaning out some comments / lint stuff. That should at least get it close to a reviewable state where I can being to take some comments / feedback on finalizing it. I can create and add adapters to a T5 model now, and train with lightning.

I'm focusing on `T5ForConditionalGeneration`.
 
Right now I'm running a test against some IMDB dataset, but the adapters aren't converging in loss like I would want. I'll look at it more closely in the next couple of days,I probably need to make sure I'm applying the inputs to the CrossAttentionAdapters and AttentionAdapters to correct inputs and with appropriate normalization.

**Comment by calpt** [comment]
> For the above mentioned deepcopy problem, I worked around it with some software engineering copying a couple of variables around.

I think that's fine as long as it only affects the adapter config. The usage of deepcopy is a bit unfortunate to us and I think we currently also don't have a cleaner to work around this problem. E.g., there's a similar case in `BartForCausalLM`.

> I'll push my updates after cleaning out some comments / lint stuff. That should at least get it close to a reviewable state where I can being to take some comments / feedback on finalizing it. I can create and add adapters to a T5 model now, and train with lightning.

Great! Let me know when you're ready for a first review or when you need any further help from us. 😃

**Comment by AmirAktify** [comment]
Ugh, there's an unfortunate name collision of `layer_norm` in AdapterLayerBaseMixin with a `layer_norm` in the original huggingface T5Block which is annoying to deal with. (The other classes dont have this kind of collision.) 

It would probably be best if that was referred to `adapter_layer_norm` in AdapterLayerBaseMixin, but that would touch too much code for me to ensure it didn't break anything. Probably the easiest solution for me would be to rename the `layer_norm` in T5Block to something else.

**Comment by AmirAktify** [comment]
There's an unfortunate name collision with the `layer_norm` used in AdapterLayerBaseMixIn and the one in `modeling_t5.py`, where makes it a bit more complicated.

**Comment by calpt** [comment]
That's indeed unfortunate. However, renaming `layer_norm` as you suggested should be possible without too much complications. I can take care of that.

**Comment by AmirAktify** [comment]
> That's indeed unfortunate. However, renaming `layer_norm` as you suggested should be possible without too much complications. I can take care of that.

I was able to work around it for now by tweaking the AdaptersMixin code. I had to switch off of the work for this week due to a project, but I should be able to dive back in this weekend. I haven't pushed majority of the code changes, so I'll get those up so the team can look at it and maybe help me push it over the line faster....sorry for the delays :(.

**Comment by AmirAktify** [comment]
So, I was able to get a `T5ForConditionalGeneration` working and converging. For an IMDB dataset, I was able to get about 88 percent accuracy on sentiment classification, using 4.5 million parameters in the adapter. 
(https://github.com/AmirAktify/adapter-transformers/blob/add_t5_adapter/src/test_t5_with_adapters_on_imdb.ipynb)

I do still have some final cleanup still left to do, but I'd appreciate some help / feedback at this point. There's some differences with the T5Model structuring compared to for instance Bart, which I had to do some slight ugly hacks to work around.

**Comment by AmirAktify** [comment]
I updated this to work with the latest master. It's ready for someone to have a quick look through the code.

 It's fast to go ahead and fix the unit tests and support `adapter_fusion`, but I did want to check in first whether the team wants me to do any major changes in the code first or the like? I did refactor the base classes some to make it work at the moment.

**Comment by calpt** [comment]
Thanks for the updates! 👍 I'll take a look.

**Comment by ashokurlana** [comment]
Does adapters currently supports mT5?

**Comment by calpt** [comment]
@ashokurlana At the moment, mT5 is not yet supported.

**Comment by ashokurlana** [comment]
Add adapters to mT5 model

**Comment by ahmedbr** [comment]
Hi,

I'm not able to use Adapter with T5 based model. Getting the following error message:


>  'T5AdapterModel' object has no attribute 'add_classification_head'

Any suggestions?
