### ISSUE TITLE
Conflicting versions of torch / (adapter-)transformers - installation confusions

### ISSUE THREAD

**Issue by dtuggener** [Adapter-Hub/adapter-transformers#130]
## Environment info
- Platform: Ubuntu 16.04.7 LTS
- Python version: 3.7 / 3.8
- PyTorch version (GPU?): no
- Tensorflow version (GPU?): no
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no
- torch version 1.8.0

## Information

Model I am using (Bert, XLNet ...): None

Language I am using the model on (English, Chinese ...): None

Adapter setup I am using (if any):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. create new venv `python3.7 -m venv venv`, activate `source venv/bin/activate`
2. install torch and adapter-transformers with pip: `python -m pip install torch adapter-transformers`
3. launch python, import torch and transformers

```
>>> import torch
>>> import transformers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.7/site-packages/transformers/__init__.py", line 135, in <module>
    from .pipelines import (
  File "/tmp/venv/lib/python3.7/site-packages/transformers/pipelines/__init__.py", line 25, in <module>
    from ..models.auto.tokenization_auto import AutoTokenizer
  File "/tmp/venv/lib/python3.7/site-packages/transformers/models/__init__.py", line 19, in <module>
    from . import (
  File "/tmp/venv/lib/python3.7/site-packages/transformers/models/albert/__init__.py", line 21, in <module>
    from ...file_utils import (
ImportError: cannot import name '_BaseLazyModule' from 'transformers.file_utils' (/tmp/venv/lib/python3.7/site-packages/transformers/file_utils.py)
```

I also tried installing torch, transformers, and then adapter-transformers, but this yields a pip dependencies conflict:
`ERROR: adapter-transformers 1.1.1 has requirement tokenizers==0.9.3, but you'll have tokenizers 0.10.1 which is incompatible.`

## Expected behavior

Flawless import :)

Thanks!

**Comment by calpt** [comment]
Hi @dtuggener,

I wasn't able to reproduce the exact error you posted. However, there are two things to ensure when setting up adapter-transformers:
1. adapter-transformers uses the same namespace as transformers, so both packages shouldn't be installed in the same environment
2. the current stable version of adapter-transformers (v1.1.1) doesn't support PyTorch 1.8 yet, we'll have that in a few weeks when synchronizing new changes from HuggingFace for our next release.

**Comment by dtuggener** [comment]
@calpt thanks for the quick reply!

> the current stable version of adapter-transformers (v1.1.1) doesn't support PyTorch 1.8 yet, we'll have that in a few weeks when synchronizing new changes from HuggingFace for our next release.

I tried forcing pytorch version 1.7.1 and now it works. `python -m pip install torch==1.7.1`
Maybe it would be helpful to have a `requirements.txt` that specifies the required/compatible versions of the needed packages?
