### ISSUE TITLE
argument parsing error due to transformers outdated version

### ISSUE THREAD

**Issue by mikygit** [Adapter-Hub/adapter-transformers#139]
Hello,
 I get the following error (see at the bottom) when parsing arguments using HFArgumentParser such as:
   parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TrainingArguments))

It appears that the bug has been fixed on huggingface side in version 4.4.2 whereas adapterHub is based on 4.4.0.
Updating only that praticular file (hf_argparser.py) helps but are you planning either to upgrade your version of transformers or integrate huggingface at some point? Would appreciate any feedbacks with other solutions or quick fixes.

Thanx.

Traceback (most recent call last):
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TrainingArguments))
  File "/opt/conda/lib/python3.7/site-packages/transformers/hf_argparser.py", line 38, in __init__
    self._add_dataclass_arguments(dtype)
  File "/opt/conda/lib/python3.7/site-packages/transformers/hf_argparser.py", line 71, in _add_dataclass_arguments
    elif hasattr(field.type, "__origin__") and issubclass(field.type.__origin__, List):
  File "/opt/conda/lib/python3.7/typing.py", line 716, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by calpt** [comment]
Hi @mikygit,
Currently, we're finalizing [v2 of adapter-transformers](https://github.com/Adapter-Hub/adapter-transformers/pull/105) which is already upgraded to the latest HF transformers version 4.4.2.

Otherwise, I think just updating the specific file is the easiest option if it fixes the error.

**Comment by calpt** [comment]
Should be resolved with the release of v2 (based on HuggingFace Transformers v4.5.1).
