### ISSUE TITLE
The versions

### ISSUE THREAD

**Issue by arkgithubforyou** [Adapter-Hub/adapter-transformers#140]
Hi,

if I understand correctly, this repo adds stuff to the original transformers library. As they use the same namespaces, only one of them could be installed to avoid confusion. Do we know which version of the transformer library each version of this repo corresponds to? As many stuff has transformer dependencies.

Thanks.

**Comment by calpt** [comment]
Hi @arkgithubforyou, your understanding is correct. The corresponding HF transformers versions underlying each adapter-transformers release can be found [in the release notes](https://github.com/Adapter-Hub/adapter-transformers/releases).

**Comment by calpt** [comment]
Closing for now, please reopen if there still is something unclear.
