### ISSUE TITLE
Language adapter training

### ISSUE THREAD

**Issue by sstojanoska** [Adapter-Hub/adapter-transformers#158]
Is there an example showing training language adapters?
In my opinion the language-modeling section of the examples is misleading because it provides scripts which can be used for language modeling but there is none showing adapters usage.

**Comment by JoPfeiff** [comment]
Hey,
The script we have been using in the past has been pushed to legacy.
We will add adapters to the new scripts ASAP.
Meanwhile the legacy code should still work:
https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/contrib/legacy/run_language_modeling.py

**Comment by sstojanoska** [comment]
Hi, thanks a lot for the quick reply :)

This legacy code does not support the HuggingFace Datasets library, right ?
So, I guess I have to change how the data is loaded to be able to train language adapter by providing a dataset name (from HF hub) ?

**Comment by calpt** [comment]
Hi @sstojanoska,

we now have modified versions of HuggingFace's new language modeling scripts with adapter support: [run_clm.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/language-modeling/run_clm.py) & [run_mlm.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/language-modeling/run_mlm.py). These support loading data from HuggingFace datasets.

**Comment by sstojanoska** [comment]
Thanks for the updates :)
