### ISSUE TITLE
Bug with load_adapter: ValueError: Found multiple possible adapters matching 'en/wiki@ukp'.

### ISSUE THREAD

**Issue by Aaronsom** [Adapter-Hub/adapter-transformers#163]
## Environment info

     
- `adapter-transformers` version: 2.0.0

## Information

Model I am using: bert-base-multilingual-cased

Relevant adapters:
en/wiki@ukp
wikiann/en@ukp

Any other language adapter with another adapter of the form $task/$language_code@ukp works.

## To reproduce

Try loading one of the language adapters with m-bert.

1.
````python
model = AutoModelWithHeads.from_pretrained("bert-base-multilingual-cased")
model.load_adapter("en/wiki@ukp")
````
2.
````
  File "C:\Users\Gregor\Anaconda3\envs\adapter\lib\site-packages\transformers\adapters\utils.py", line 260, in find_in_index
    raise ValueError("Found multiple possible adapters matching '{}'.".format(identifier))
ValueError: Found multiple possible adapters matching 'en/wiki@ukp'.
````

## Expected behavior

The adapter is loaded normally.

## Why this happens
Line 252 in transformers\adapters\utils.py calls _dict_extract() (in the same utils.py).
The problematic adapter wikiann/en@ukp matches due to the 'en' in the else-part (line 230) and is yielded which then results in two possible adapters matching 'en/wiki@ukp'.

The else-part should (as far as I can see) not be used if both primary_key and secondary_key is given and should only be evaluated if only a primary_key is given to allow for e.g. `mode.load_adapter("cs")` instead of `mode.load_adapter("cs/wiki@ukp")`.

**Comment by Aaronsom** [comment]
Changing line 230 in  transformers\adapters\utils.py to ``elif secondary_key is None:`` results in the English language adapter loading correctly but I do not know if this has other unintended side-effects.

**Comment by calpt** [comment]
Thanks for the detailed bug report.

> Changing line 230 in transformers\adapters\utils.py to elif secondary_key is None: results in the English language adapter loading correctly but I do not know if this has other unintended side-effects.

I think this solution should work. Would you mind opening a PR for it?

**Comment by Aaronsom** [comment]
It's open

https://github.com/Adapter-Hub/adapter-transformers/pull/164
