### ISSUE TITLE
Adapter for fr/wiki: non_linearity and reduction_factor?

### ISSUE THREAD

**Issue by piegu** [Adapter-Hub/adapter-transformers#170]
Hello,

In the page [Adapter for fr/wiki](https://adapterhub.ml/adapters/ukp/bert-base-multilingual-cased-fr-wiki_pfeiffer/), there are the following informations about `Architecture`:

```
Name: pfeiffer
Non-linearity: gelu
Reduction factor: 2
```

But in the Configuration list, I see:

```
"non_linearity": "relu"
"reduction_factor": 16
```

Why are they different?

**Comment by calpt** [comment]
Hi @piegu, the information listed in the _Architecture_ section is the correct one, the one in the configuration dict is wrong. We'll fix that on the website side, thanks for mentioning!
