### ISSUE TITLE
AutoModelWithHeads class: to be used or not?

### ISSUE THREAD

**Issue by piegu** [Adapter-Hub/adapter-transformers#171]
Hello,

The difference between the scripts [run_glue.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/text-classification/run_glue.py) and [run_glue_alt.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/text-classification/run_glue_alt.py) is described as following in the latter:

`The only change is replacing AutoModelForSequenceClassification with AutoModelWithHeads class for better adapter support.`

I would like to understand why the Adapter-Transformers team published theses 2 versions. 

I noticed the same diference between examples from the [Colab notebooks](https://github.com/Adapter-Hub/adapter-transformers/tree/master/notebooks#adapterhub-notebooks) and [documentation](https://docs.adapterhub.ml/), and scripts like [run_mlm.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/language-modeling/run_mlm.py) or [run_ner.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/token-classification/run_ner.py):

- in the former, examples use the `AutoModelWithHeads` class
- in the latter, examples does not

I'm wondering why and what are the consequences. In my opininon, when we do not use the `AutoModelWithHeads` class, the corresponding weights are not trained and not saved when the trained adapter is saved by `model.save_adapter()`. 

It's a problem, no?

**Comment by calpt** [comment]
Hi,

First, and most important: adapter training works identically with either option and `save_adapter()` will save the trained weights in all cases.

The reason why both options exist is a bit technical:
- `AutoModelForSequenceClassification` (similar to `AutoModelForTokenClassification` etc.) are the classes provided in Transformers by HuggingFace. We kept them for full compatibility with the original library.
- `AutoModelWithHeads` is unique to adapter-transformers. The big advantage of this class is that it allows for multiple, flexible prediction heads within one model. E.g. you can add two adapters both with their prediction head and then quickly switch between them in one model:

```
model = AutoModelWithHeads.from_pretrained(...)
model.add_adapter("classification")
model.add_classification_head("classification")
model.add_adapter("tagging")
model.add_tagging_head("tagging")

model.active_adapters = "classification"
# will use classification adapter and head...
model.active_adapters = "tagging"
# will use tagging adapter and head...
```

Also see: https://docs.adapterhub.ml/prediction_heads.html

Hope this clears things up!

**Comment by piegu** [comment]
Hello @calpt.

Thank you for your very clear answer.

One more question: I understand for task-trained models the importance of keeping the heads trained, as well as the adapters of course.

But what about saving the head of a fine-tuned language model, trained with adapters? 
Can you give us the code? Thanks.

**Comment by calpt** [comment]
> But what about saving the head of a fine-tuned language model, trained with adapters?

As described [in our docs](https://docs.adapterhub.ml/prediction_heads.html), `save_adapter()` will save the adapter modules **and** the head of the LM (if available). Alternatively, you can use `save_head()`/ `load_head()` to save/ load only the head without the adapters.
