### ISSUE TITLE
ReLU or GeLU for Adapters?

### ISSUE THREAD

**Issue by piegu** [Adapter-Hub/adapter-transformers#173]
Hello,

Adapters are described with a different non-linear activation function in papers from the Adapter-Transformers team: they are described with a ReLU in the page 3 of "[MAD-X: An Adapter-Based Framework for Multi-Task Cross-Lingual Transfer](https://arxiv.org/abs/2005.00052)" (October 2020) but with a GeLU in the page 3 of "[UNKs Everywhere: Adapting Multilingual Language Models to New Scripts](https://arxiv.org/abs/2012.15562)" (April 2021).

Why this difference and which non-linear activation function to choose, respectively, for language and task adapters?

**Comment by JoPfeiff** [comment]
We've experimented with both and there doesn't seem to be a big difference. 
GeLU is simply the more "natural" activation function for BERT

**Comment by calpt** [comment]
Closing for now, please reopen if the question has not been fully addressed.
