### ISSUE TITLE
How to retrieve AdapterFusion activations for each layer?

### ISSUE THREAD

**Issue by agrov** [Adapter-Hub/adapter-transformers#174]
Hi,

I am currently experimenting with AdapterFusion for my thesis. I would like to understand which related task impacts the performance of the target task layer by layer. Could you please explain how I can replicate the results in Figure 4 of your AdapterFusion paper (https://arxiv.org/pdf/2005.00247.pdf) for my tasks?

Best,
Anjali

![image](https://user-images.githubusercontent.com/22557611/118390208-2dea1b00-b62e-11eb-8f56-a8a7d8958ffe.png)

**Comment by daandouwe** [comment]
A while back I asked a similar question and got a great response, which allowed me to create these plots. See this comment for that: https://github.com/Adapter-Hub/adapter-transformers/issues/83#issuecomment-728992049

The summary is (assuming the roberta model):
```python
model.roberta.encoder.layer[layer_i].output.adapter_fusion_layer['<name of the fusion layer>'].recent_attention
```

**Comment by agrov** [comment]
That's awesome. Thank you!

**Comment by agrov** [comment]
Hey @daandouwe, just wondering if you were able to create an example script for achieving the attention scores? Is it possible to get the "recent_attention" from an already trained adapter fusion model?

Thanks!
