### ISSUE TITLE
Saving heads post training of adapter fusion

### ISSUE THREAD

**Issue by jithu-chandran** [Adapter-Hub/adapter-transformers#180]
# 🚀 Feature request

Unlike for save_adapter(), the save_adapter_fusion() module does not seem to have the option of saving with heads. Hence, I had to call the save_head() function separately to save the heads of the adapter fusion. Would be nice if the functionality to save the heads is added to save_adapter_fusion().

## Motivation
To save heads along with adapter fusion in a single line of code.

**Comment by calpt** [comment]
Hi,

Thanks for the suggestion, this makes a lot of sense. We currently don't have a boolean `with_head` flag on save_adapter_fusion() as the fusion layer and the head usually don't have the same name, so the link between fusion and head is not as clear. So, there are multiple ways to implement this:
1.) As with save_adapter(), save a head with the same name. However, for a setup like `Fuse("a", "b")`, this would search for a head named "a,b", which might not be desired.
2.) Save the currently active head
3.) Provide a string to `with_head` and always save the head with that name.

Is there any preferred option from your side?
