### ISSUE TITLE
How to load Trained Adapter Fusion Model?

### ISSUE THREAD

**Issue by agrov** [Adapter-Hub/adapter-transformers#188]
Hi,

I am experiencing poor performance on test data (ROC AUC of 0.45 on test vs 0.87 on validation data) after training the model using Adapter Fusion. I suspect it has something to do with how I am loading the trained fusion adapter. Could you please take a look below and let me know if I am missing something here?

```
model = AutoModelWithHeads.from_pretrained(model_args.model_name_or_path,
                                           from_tf=bool(".ckpt" in model_args.model_name_or_path),
                                           config=config,
                                           cache_dir=model_args.cache_dir,
                                           )
model.add_classification_head(
    data_args.task_name,
    num_labels=num_labels,
    id2label={i: v for i, v in enumerate(label_list)} if num_labels > 0 else None,
    overwrite_ok=True,
    multilabel=True if task_type == 'multilabel' else False
)

model.load_adapter(
    'task1',
    "text_task", config=PfeifferConfig(), with_head=False
)

model.load_adapter(
    "task2",
    "text_task",config=PfeifferConfig(), with_head=False)

model.load_adapter(
    "task3",
    "text_task",config=PfeifferConfig(), with_head=False)

model.load_adapter(
    "task4",
    "text_task",config=PfeifferConfig(), with_head=False)

model.load_adapter_fusion("task1,task2,task3,task4")

adapter_setup = [
    [
         "task1",
         "task2",
         "task3",
         "task4"
    ]
]
model.set_active_adapters(adapter_setup[0])

    if training_args.do_eval:
        logger.info("*** Evaluation on Test Dataset ***")
        eval_datasets = [test_dataset]
        eval_result = trainer.evaluate(eval_dataset=eval_dataset)
        output_eval_file = os.path.join(training_args.output_dir, f"eval_results_{task}.txt")
```

**Comment by agrov** [comment]
Hi @calpt , could you please help me with this problem? I am using AdapterFusion for my master's thesis and have been stuck with the above-mentioned problem for a few days. It would be really helpful if you could let me know if I am missing something while loading the AdapterFusion model. Thank you!

**Comment by calpt** [comment]
Hi @agrov, from your code, the problem seems to be that you don't reload a pre-trained classification head for your task, but add a randomly initialized head (with `add_classification_head()`). For using the head trained with AdapterFusion, please make sure to save it after training:
```
model.save_head("/path/to/save/dir", data_args.task_name)
```
(note that this should be called in addition to `save_adapter_fusion()`) and then reload it for evaluation: 
```
model.load_head("/path/to/save/dir")
```
Hope this helps!

**Comment by agrov** [comment]
It worked. Thank you!
