### ISSUE TITLE
Hugging Face version

### ISSUE THREAD

**Issue by piegu** [Adapter-Hub/adapter-transformers#191]
## Environment info
     
`adapter-transformers` version: 2.0.1

## Information

The problem arises when checking the version of the `transformers` library.

## To reproduce

 In a notebook with the running kernel `adapters-transformers`, run the following code in a cell:

`import transformers; print('transformers:',transformers.__version__)`

Result: `transformers: 2.0.0`

## Expected behavior

1. The true version of the `transformers` library (4.5.1 in the [release notes](https://github.com/Adapter-Hub/adapter-transformers/releases)).
2. More, it appears that the `transformers` version of the `adapter-transformers` library is not synchronised to the last `transformers` version of Hugging Face (4.7.0 on the 06/21/2021).

**Comment by calpt** [comment]
`transformers.__version__` outputs the version of adapter-transformers, so 2.0.0, 2.0.1 are the correct versions. The underlying HuggingFace transformers version is provided by `transformers.__hf_version__`. This is v4.5.1 on the current stable release, v4.6.1 on the `develop` branch of our repo and the newest v4.8.0 on the most recent PR: https://github.com/Adapter-Hub/adapter-transformers/pull/194

**Comment by piegu** [comment]
Thanks for the clarification. 

Is there any date for the synchronization of `transformers` libraries on the current stable release of `adapter-transformers `(`transformers`: 4.8.1, 06/24/2021)?

**Comment by calpt** [comment]
No exact date, but this should happen within the next 2 weeks.

**Comment by calpt** [comment]
v2.1.0 of adapter-transformers upgrades the underlying transformers version to v4.8.2
