### ISSUE TITLE
Question-Answering script: Why Fuse and not Stack?

### ISSUE THREAD

**Issue by piegu** [Adapter-Hub/adapter-transformers#196]
Hello,

At the [line 352 of the script run_qa.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/question-answering/run_qa.py#L352), there is a `Fusion` between the QA task and lang adapters as following:
`model.set_active_adapters(Fuse(lang_adapter_name, task_name))`

Firtsly, this is surprising not to see a `Stack` between theses 2 adapters as is done in the corresponding notebook [Zero-Shot Cross-Lingual Transfer using Adapters](https://github.com/Adapter-Hub/adapter-transformers/blob/master/notebooks/04_Cross_Lingual_Transfer.ipynb).

More, there is no `add_fusion()` or `load_adapter_fusion()` before this line of code. As written in the [documentation](https://docs.adapterhub.ml/adapter_composition.html?highlight=stack#fuse), it is mandatory.

Therefore, my 2 questions are:
1. What is the recommended method to deal with a task adapter and its lang one: `Stack` or `Fusion`?
2. Depending of the answer, the script and/or its corresponding notebook must be updated.

cc @hSterz 

**[ EDIT ]**: as the task adapter does not exist, it is going to be hard to create it and make a fusion with its lang adapter at the same time. The `run_qa.py` script must be updated I think.

**Comment by hSterz** [comment]
Yes, you are right is should be 'Stack' instead of  'Fuse'. We will update the script.
