### ISSUE TITLE
getting error when passing `with_head=False` to load_adapter

### ISSUE THREAD

**Issue by mahmoudyusuf94** [Adapter-Hub/adapter-transformers#198]
I use the following code to load adapter to my bert model of type `BertModel` :

```
adapter1_conf = AdapterConfig.load("pfeiffer")
adapter1_name = model.bert.load_adapter("dialect/arabic@mapmeld", config=adapter1_conf, model_name='aubmindlab/bert-base-arabert', with_head=False)
```

  However, I get the following error:

```
Traceback (most recent call last):
  File "modeling.py", line 347, in <module>
    trainer_class.train_and_evaluate_with_multiple_seeds(1, seeds_from_config=True, eval_on_train=False)
  File "modeling.py", line 314, in train_and_evaluate_with_multiple_seeds
    accuracy_agg, model_pathes = self.train_with_multiple_seeds(no_times, seeds_from_config=seeds_from_config)
  File "modeling.py", line 248, in train_with_multiple_seeds
    temp_accuracy, best_model_path = self.train()
  File "modeling.py", line 96, in train
    adapter1_name = model.bert.load_adapter("dialect/arabic@mapmeld", config=adapter1_conf, model_name='aubmindlab/bert-base-arabert', with_head=False)
  File "/usr/local/lib/python3.7/dist-packages/transformers/adapters/model_mixin.py", line 347, in load_adapter
    adapter_name_or_path, config, version, model_name, load_as, leave_out=leave_out, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/transformers/adapters/loading.py", line 401, in load
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/transformers/adapters/utils.py", line 405, in resolve_adapter_path
    adapter_name_or_path, model_name, adapter_config=adapter_config, version=version, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/transformers/adapters/utils.py", line 354, in pull_from_hub
    download_path = download_cached(file_entry["url"], checksum=checksum, checksum_algo=checksum_algo, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/adapters/utils.py", line 115, in download_cached
    output_path = get_from_cache(url, cache_dir=cache_dir, **kwargs)
TypeError: get_from_cache() got an unexpected keyword argument 'with_head' 
```

**When I remove the `with_head` parameter it works, but I need to remove the head from the adapter.
Any idea?**

**Comment by calpt** [comment]
The `with_head` parameter is only present for model classes that actually have a prediction head (`AutoModelForSequenceClassification`, `AutoModelWithHeads`, `BertModelWithHeads` etc.). Base model classes (`BertModel`, `RobertaModel` etc.) don't have this parameter for `load_adapter()` as adapters are loaded without heads in any case. From your code, it seems you're calling `load_adapter()` from a base model class (model.**bert**.load_adapter()).

**Comment by mahmoudyusuf94** [comment]
@calpt  so even if the adapter description says it has a prediction head, the head will not be loaded in my case?
I use this adapter:
https://adapterhub.ml/adapters/mapmeld/bert-base-arabert-ar-dialect/
and it has a classification head that I don't want to use

**Comment by calpt** [comment]
Yes, that's right. `BertModel` and similar classes cannot make use of a prediction head, even if available. Only classes that support heads (`XForSequenceClassification` etc. and `XModelWithHeads`) will load prediction heads by default.

**Comment by mahmoudyusuf94** [comment]
Thank you @calpt
