### ISSUE TITLE
Error loading static heads into classes with flexible heads

### ISSUE THREAD

**Issue by esha-sg** [Adapter-Hub/adapter-transformers#219]
## Environment info

     
- `adapter-transformers` version: 2.1.0
- Platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.11
- PyTorch version (GPU?): 1.9.0+cu102 (True)
- Tensorflow version (GPU?): 2.5.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

## Information

Model I am using (Bert, XLNet ...): Bert

Language I am using the model on (English, Chinese ...): English

Adapter setup I am using (if any):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

1. I am using the automatic conversion script here https://docs.adapterhub.ml/prediction_heads.html#automatic-conversion to load static heads into classes with flexible heads.
2. Running the code initially does not produce the error.
3. Running the same code again produces below provided error.

```
from transformers import AutoModelForSequenceClassification, AutoModelWithHeads
static_head_model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")
static_head_model.add_adapter("test")
static_head_model.save_adapter(temp_dir, "test")

flex_head_model = AutoModelWithHeads.from_pretrained("bert-base-uncased")
flex_head_model.load_adapter(temp_dir)

assert "test" in flex_head_model.config.adapters
assert "test" in flex_head_model.heads
```
```
/usr/local/lib/python3.7/dist-packages/transformers/adapters/model_mixin.py in load_adapter(self, adapter_name_or_path, config, version, model_name, load_as, source, with_head, custom_weights_loaders, leave_out, id2label, **kwargs)
    637             leave_out=leave_out,
    638             id2label=id2label,
--> 639             **kwargs,
    640         )
    641 

/usr/local/lib/python3.7/dist-packages/transformers/adapters/model_mixin.py in load_adapter(self, adapter_name_or_path, config, version, model_name, load_as, source, custom_weights_loaders, leave_out, id2label, **kwargs)
    426                     loading_info=kwargs.get("loading_info", None),
    427                     main_load_name=load_name,
--> 428                     id2label=id2label,
    429                 )
    430         return load_name

/usr/local/lib/python3.7/dist-packages/transformers/adapters/loading.py in load(self, save_directory, load_as, loading_info, **kwargs)
    673                         head_name,
    674                         custom_label2id or config.get("label2id"),
--> 675                         num_labels=config.get("num_labels"),
    676                     )
    677                 else:

/usr/local/lib/python3.7/dist-packages/transformers/adapters/head_utils.py in get_head_config_and_rename_list(model_class_name, head_name, label2id, num_labels)
    211     # config
    212     config = data["config"]
--> 213     if config["head_type"] == "multiple_choice":
    214         config["num_choices"] = num_labels
    215     else:

KeyError: 'head_type'
```

## Expected behavior

The heads should be loaded as expected into class with flexible heads.

**Comment by calpt** [comment]
Hi @esha-sg, this is a known bug in v2.1.0, please upgrade to the latest version of adapter-transformers (v2.1.2) and check if this resolves your issue.

**Comment by esha-sg** [comment]
Thanks @calpt. The latest version does not have this issue. Closing this issue.
