### ISSUE TITLE
AdapterTransformer with Pytorch 1.9 fails for multi-GPU

### ISSUE THREAD

**Issue by hchoi-moveworks** [Adapter-Hub/adapter-transformers#227]
## Environment info

     
- `adapter-transformers` version: 2.1.2
- Platform: 
- Python version: 3.6
- PyTorch version (GPU?): 1.9.0
- Tensorflow version (GPU?): NA
- Using GPU in script?: Yes (multi GPU) 
- Using distributed or parallel set-up in script?:
 - Using torch.nn.DataParallel + 2 GPU's
 
## Information

Model I am using (Bert, XLNet ...):
DistillBERT Model with Adapter + Classification Head

Language I am using the model on (English, Chinese ...):
English

Adapter setup I am using (if any):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ x] my own task or dataset: (give details below)

## To reproduce
NA

## Expected behavior

Model forward call function works. 

0) Error
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking arugment for argument weight in method wrapper_native_layer_norm)
```

1) Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals))
  File /absl/app.py", line 312, in run
    _run_main(main, args)
  File "/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
    outputs = self._model(*inputs)
  File "/home//torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()


RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File python3.6/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 571, in forward
    adapter_names=adapter_names,
  File "python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "python3.6/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 516, in forward
    **kwargs,
  File "python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/python3.6/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 328, in forward
    **kwargs,
  File "python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File python3.6/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 271, in forward
    sa_output = self.attention_adapters.adapters_forward(sa_output, x, **kwargs)  # (bs, seq_length, dim)
  File python3.6/site-packages/transformers/adapters/layer.py", line 464, in adapters_forward
    hidden_states = self.transformer_layer_norm(hidden_states + input_tensor)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/python3.6/site-packages/torch/nn/modules/normalization.py", line 174, in forward
    input, self.normalized_shape, self.weight, self.bias, self.eps)
  File "python3.6/site-packages/torch/nn/functional.py", line 2346, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking arugment for argument weight in method wrapper_native_layer_norm)
```

3) Similar errors:
 - https://discuss.pytorch.org/t/runtimeerror-expected-all-tensors-to-be-on-the-same-device-but-found-at-least-two-devices-while-using-layernorm/125503
 
 
 Are LayerNorm created during `forward` call in the AdapterHub Module? It seems like device placement of weights for layer norms are incorrect.

**Comment by cody-moveworks** [comment]
Here is minimal code that reproduces the issue above:

```
from transformers import AutoModelWithHeads, AutoTokenizer
import torch
import torch.nn as nn

# Load model with adapter and put it on GPU 0
model = AutoModelWithHeads.from_pretrained('distilbert-base-uncased')
model.add_adapter('toy-task', config=None)
model.add_classification_head(head_name='toy-task', num_labels=2)
model = model.to(device=torch.device('cuda:0'))

# Wrap it in DataParallel and have it act on GPUs 0 and 1
model = nn.DataParallel(model, device_ids=[0, 1])

# Do inference with the wrapped model... should fail
tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased')
inputs = tokenizer(
    text=['AdapterHub is awesome!', 'Adapters are super helpful!'],
    padding=True,
    truncation=True,
    return_tensors='pt',
    return_attention_mask=True,
    return_token_type_ids=True,
)
outputs = model(
    input_ids=inputs['input_ids'],
    attention_mask=inputs['attention_mask'],
    token_type_ids=inputs['token_type_ids'],
    adapter_names='toy-task',
    head='toy-task',
    return_dict=False,
)
print(outputs)
```

**Comment by calpt** [comment]
Hey @hchoi-moveworks and @cody-moveworks,

thanks for the detailed bug report. We found and fixed an issue of our implementation with `DataParallel` (which was indeed related to the LayerNorm). The fixed version is now on our master branch. Please let me know if this resolves your issue.

**Comment by hchoi-moveworks** [comment]
Thank you @calpt for the prompt fix! 

We have a few follow up questions :-) 

Was this an issue only for `DataParallel`?  We are currently using adapter-hub with specific version (e.g. 2.1.2) and if this is only an issue with `DataParallel` we can also try with `DistributedDataParallel` and try to keep use the current version instead of waiting for the next branch cut. 

Also, do you know when the next branch cut/release date with this fix included will be?

**Comment by calpt** [comment]
@hchoi-moveworks The issue was caused by the mechanism `DataParallel` uses to distribute the model to different devices (copying module by module). This corrupted references between modules we require in the DistilBERT implementation. I haven't tried if there was a similar problem with `DistributedDataParallel`.

Regarding the next release, we expect to finish that within the next two weeks (also including new features and HF transformers upgrade).

**Comment by hchoi-moveworks** [comment]
Looping back regarding official release of adapterhub. 

It would be really great if we could have this fix as part of the official release. :) It seems like there were no additional releases after 2.1.2 [1]

Please let us know if there's an approximate timeline! The current adapterhub master branch includes multiple fixes for us and we would love to be able to use an official release. 

[1]: https://pypi.org/project/adapter-transformers/#history
