### ISSUE TITLE
How to use adapter on latest transformers repo?

### ISSUE THREAD

**Issue by sbmaruf** [Adapter-Hub/adapter-transformers#230]
Recent transformers repo supported many new feature and corrected a lot of bugs. I understand this is a branch of huggingface transformers repo. But If I want to use `adapters` in latest huggingface transformers main branch, do I have to manually merge them or is there any other workaround for that?

**Comment by calpt** [comment]
Hi @sbmaruf, we try to merge new changes from HuggingFace's repo on a regular basis. The current status on the master branch of this repo is based on transformers v4.9.2 and we have a sync with HuggingFace's latest v4.10.3 [on the way](https://github.com/Adapter-Hub/adapter-transformers/pull/234).

**Comment by xloem** [comment]
Is there documentation of the workflow for this, so that users can try newer models before merges are made?
