### ISSUE TITLE
Where to put the code if I want to customize the fusion layers?

### ISSUE THREAD

**Issue by zhuang-li** [adapter-hub/adapter-transformers#235]
## Environment info

     
- `adapter-transformers` version: v2
- Platform: AWS, V100 GPU
- Python version: 3.8
- PyTorch version (GPU?): 1.7.1

## Details
Where to put the code if I want to customize the fusion layers?

Hi if I don't want to use Fuse or Stack and want to customize the fusion layer instead, where should I put the code?
Thank you for resolving my questions.

**Comment by calpt** [comment]
Hey @zhuang-li,
the fusion layer implementation is located in a module class in the `modeling.py` file [here](https://github.com/Adapter-Hub/adapter-transformers/blob/f5fdcc3678ee7c0ade527e221c3d995df9845b03/src/transformers/adapters/modeling.py#L152). So one way to customize the implementation could be to modify this class.
