### ISSUE TITLE
Support for custom embedding

### ISSUE THREAD

**Issue by hchoi-moveworks** [Adapter-Hub/adapter-transformers#238]
Does AdapterHub support model with custom embeddings? That is, let us imagine a model where
- all attention layers are same as Huggingface BERT model that Adapterhub supports
- BertEmbedding[1] is replaced with **custom** embedding module. 

[1]: https://github.com/huggingface/transformers/blob/master/src/transformers/models/bert/modeling_bert.py#L167-L174

With this as base model, would adapterhub work? If adding adapters only impact attention blocks of the base model, I believe this should work, but I wanted to confirm as there maybe internal details that I do not know.

**Comment by JoPfeiff** [comment]
This definitely works and we are currently working on adding this type of modularity (similar to the different prediction heads). This is explicitly what we did in our paper [UNKs everywhere](https://arxiv.org/abs/2012.15562), to be presented at EMNLP 2021. 
This should be available (at least in a branch) in the upcoming weeks.
