### ISSUE TITLE
How to load pre-trained adapters to tune on my downstream task ?

### ISSUE THREAD

**Issue by SinclairCoder** [adapter-hub/adapter-transformers#247]
hi，thanks for your great work! I am new to Adapter-transformers. In my recent exp, I wanna load pre-trained adapters to continue to tune on my downstream task.  I look up the [docs](https://docs.adapterhub.ml/) and don't find any solutions or related examples. Could you give me some suggestions? Thanks very much.

```
task_name = 'MRC'
config = AdapterConfig.load("pfeiffer")
self.bert.load_adapter("qa/squad1@ukp", config=config)
# self.bert.add_adapter(task_name) #, config=adapter_config)
self.bert.train_adapter(task_name)
self.bert.set_active_adapters(task_name)
```
there is my code with bug `ValueError: Unable to resolve adapter without the name of a model. Please specify model_name.`  just for reference.

**Comment by calpt** [comment]
Hey @SinclairCoder,

the resolving of pre-trained adapters within the `load_adapter()` method is dependent on the pre-trained base model (e.g. bert-base-uncased, roberta-base etc.). In many cases, adapter-transformers will be able to infer this name automatically (e.g. if you load a model using `from_pretrained()`. If this is not possible, the `load_adapter()` methods expects the name of a pre-trained model as a parameter.

So, in your case, if you would like to load an adapter trained for e.g. bert-base-uncased, please try to add `model_name="bert-base-uncased"` to the `load_adapter()` method call.

Hope this helps :)
