### ISSUE TITLE
Fine tuning an already adapter-injected model

### ISSUE THREAD

**Issue by SondreWold** [adapter-hub/adapter-transformers#248]
Hi, 

I'm replicating a study using adapters [1] which predates this framework.

As I interpret the paper and their source code, they train a single-task adapter, using the Houslby configuration, on the mlm objective on a corpus. Then, loading the entire model with the adapter, they fine-tune on the GLUE tasks. 

I have tried to replicate this using AdapterHub. Using your example scripts, I am quite sure that the first step is done correctly. However, when fine-tuning the entire model on a GLUE task, I want to make sure that both the weights of the base model and the added parameters from the adapter are included in the forward pass.

Are the following steps enough to achieve this behavior? 

1. Load the adapter-injected model (bert-base-uncased, with an adapter named mlm)
2. Activate the adapter with: `model.train_adapter(["mlm"])` and `model.set_active_adapters(["mlm"])`
3. Unfreeze the normal set of parameters with `model.freeze_model(False)`
4. Continue as usual 

[1]: [Lauscher et al. (2020](https://arxiv.org/abs/2005.11787)

**Comment by calpt** [comment]
Hi @SondreWold,

based on your description, the steps you listed sound correct.
