### ISSUE TITLE
Using cross-lingual task fusion with a target language adapter

### ISSUE THREAD

**Issue by isspek** [Adapter-Hub/adapter-transformers#251]
## Environment info

     
- `adapter-transformers` version: 2.2.0
- Platform: Linux-5.4.0-1059-aws-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.9.1+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## Details

I am working on a multilingual classification task and would like to evaluate the adapters on cross-lingual transfer. The dataset of tasks contains a small size of the training set for each language. I got bad results when I only train the dataset on a monolingual dataset and transfer it to the new language. So next step I tried is to train a fusion adapter on cross-lingual data with 3 languages and then use the fusion on the testing set (2 languages). 

I can get an adapter for each training language by using language adapters:
   
```
# load pre-trained models from Huggingface
    config = AutoConfig.from_pretrained(
        pretrained_model,
        num_labels=2,
    )
    model = AutoModelWithHeads.from_pretrained(
        pretrained_model,
        config=config,
    )

    if args.lang != 'none':
        lang = args.lang
        lang_adapter_config = AdapterConfig.load(
            None,
            leave_out=[11])  # mad-x
        
        lang_adapter_names = LANG_ADAPTERS[lang]
        if isinstance(lang_adapter_names, list):
            lang_adapters = []
            for lang_adapter in lang_adapter_names:
                lang = lang_adapter.split('/')[0]
                lang_adapters.append(model.load_adapter(
                    lang_adapter, config=lang_adapter_config, load_as=lang))
            
            model.add_adapter_fusion(lang_adapters)
        else:    
            model.load_adapter(LANG_ADAPTERS[lang], config=lang_adapter_config)
        
        
        # Add a new adapter
        model.add_adapter(task_name)

        # Add a matching classification head
        model.add_classification_head(
            task_name,
            num_labels=num_labels,
        )

        if lang == 'bg':
            # activate the language adapter
            model.active_adapters = Stack(Fuse('ru', 'en'), task_name)
        else:
            model.active_adapters = Stack(lang, task_name)

    else:
        # Add a new adapter
        model.add_adapter(task_name)

        # Add a matching classification head
        model.add_classification_head(
            task_name,
            num_labels=num_labels,
        )

    # Activate the adapter
    model.train_adapter(task_name)
```

Once I get the task adapters. I can train a fusion adapter:

```
    # Add fusions
    adapter_setup = args.adapter_setup
    model.load_adapter(args.task_a, with_head=False)
    model.load_adapter(args.task_b, with_head=False)
    model.load_adapter(args.task_c, with_head=False)

    model.add_adapter_fusion(adapter_setup)
    model.add_classification_head(
        task_name,
        num_labels=num_labels,
    )
    model.set_active_adapters([adapter_setup])
    model.train_fusion([adapter_setup])
```

However, after training I cannot use the fusion with the target language adapter:
```
    # Load Fusion Adapters
    logger.info('Adding task adapters')
    model.load_adapter(args,task_a, with_head=False)
    model.load_adapter(args.task_b, with_head=False)
    model.load_adapter(args.task_c, with_head=False)

    adapter_setup = args.adapter_setup
    model.load_adapter_fusion(FUSION_PATH)
    model.set_active_adapters([adapter_setup])
    model.load_head(FUSION_PATH, task_name)
    
    if args.lang:
        trg_lang = args.trg_lang
        lang_adapter_config = AdapterConfig.load(None, leave_out=[11])
        trg_lang_adapter_names = LANG_ADAPTERS[trg_lang]
        
        if isinstance(trg_lang_adapter_names, list):
            trg_lang_adapters=[]
            for trg_lang_adapter in trg_lang_adapter_names:
                _trg_lang = trg_lang_adapter.split('/')[0]
                trg_lang_adapters.append(model.load_adapter(
                   trg_lang_adapter, config=lang_adapter_config, load_as=_trg_lang))
            
            model.add_adapter_fusion(trg_lang_adapters)
        else:
            model.load_adapter(trg_lang_adapter_names, config=lang_adapter_config, load_as=trg_lang)
        
        if trg_lang=='bg':
            model.active_adapters = Stack(Fuse('ru', 'en'), task_name)
        else:
            model.active_adapters = Stack(trg_lang, task_name)
```
The error message I received is `ValueError: No adapter with name 'task_fusion_world_language_with_lang_adapter' found. Please make sure that all specified adapters are correctly loaded. ` where refers to` task_name` in the code.

I guess, the way I use the fusion adapter with the language adapter is wrong. I would appreciate it if you guide me on how I can set up it correctly. Thanks in advance.

**Comment by calpt** [comment]
Hey @isspek,

I'm afraid I'm not quite sure what you are trying to achieve. Here's how I understood your problem setting, please correct me if I'm wrong:

- you have a multilingual classification task, let's say in languages "lang_a", "lang_b", "lang_c", "lang_d". Now the goal is to train adapters on "lang_a", "lang_b" & "lang_c" and transfer to "lang_d" for evaluation.
- the first step is to train monolingual adapters on each language by stacking upon a language adapter for the corresponding language, e.g.:
```python
model.load_adapter("lang_a")  # pre-trained lang adapter
model.add_adapter("task_a")   # task adapter trained on dataset portion in "lang_a"
model.train_adapter("task_a")
model.active_adapters = Stack("lang_a", "task_a")
```
After this, we would have one task adapter per language, i.e. "task_a" for "lang_a" and so on.
- Now, as transferring a single adapter to the target language does not give good results, we would like to transfer all adapters to the target language ("lang_d" in the example) using fusion:
```python
# source task adapters trained in step 1
fusion_adapters = ["task_a", "task_b", "task_c"]

for adapter_name in fusion_adapters:
  model.load_adapter(adapter_name)

# load language adapter for target language
model.load_adapter("lang_d")

# add a fusion layer of the task adapters
model.add_adapter_fusion(fusion_adapters)
model.train_adapter_fusion(fusion_adapters)

# activate the adapter stacks
# as we transferred to the target language, stack all task adapters with the target language adapter (MAD-X setup)
model.active_adapters = Fuse(
  Stack("lang_d, "task_a"),
  Stack("lang_d", task_b"),
  Stack("lang_d", task_c")
)
# train & evaluate fusion setup ...
```
The important part here is the nesting of the `Fuse` and `Stack` blocks (see [here](https://docs.adapterhub.ml/adapter_composition.html)). The code just gives the general idea, I haven't tested it myself.

Does this roughly correspond to what you tried to achieve? If not, please try to give a more concrete example of the setup and I'm happy to further.

**Comment by isspek** [comment]
Hi @calpt,

You correctly described my problem. Thanks for the code snippet and the link for the block. This would help me a lot. 

Kind regards,
Ipek

**Comment by ahtamjan** [comment]
hello, I have the same problem and this helped me a lot. And I also want to know how can I add a classification head upon 3 task fusion layer?
