### ISSUE TITLE
Add documentation how to use loaded adapters without prediction head

### ISSUE THREAD

**Issue by arueckle** [Adapter-Hub/adapter-transformers#26]
# 🚀 Feature request

A description on how to manually pass the adapter composition to `model.forward()`

## Motivation

I am doing this right now and cannot remember the exact naming. Checked docs, didn't find it. Now need to check code

**Comment by sosuperic** [comment]
Is this referring to / related to https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/modeling_bert.py#L679? Or is adapter *composition* something else?

If I'm understanding correctly, if you're using a `BertModelWithHeads` (i.e. you trained a [Task Adapter](https://docs.adapterhub.ml/training.html#train-a-language-adapter) with `AdapterType.text_task`), then you can just call [`set_active_adapters`](https://docs.adapterhub.ml/classes/bert_mixins.html#transformers.adapter_bert.BertModelHeadsMixin.set_active_adapters). However, `set_active_adapters` is only defined for [`BertModelHeadsMixin`](https://docs.adapterhub.ml/classes/bert_mixins.html#transformers.adapter_bert.BertModelHeadsMixin).

In my case, I trained a [Language Adapter](https://docs.adapterhub.ml/training.html#train-a-language-adapter), where I continued pre-training BERT on my own dataset. This model doesn't have prediction heads (i.e. I can't do the above), so I had to do the following in my forward pass. This took me some time to find as well -- I don't think it's in the docs, and I had to search through the code.
```
self.masked_bert_model = BertForMaskedLM.from_pretrained(bert_model_name)
adapter_name = self.masked_bert_model.load_adapter(ADAPTER_DIR)

...

logits = self.masked_bert_model(
                input_ids=tokens_tensor.to(self._model_device),
                token_type_ids=segments_tensor.to(self._model_device),
                attention_mask=attention_mask_tensor.to(self._model_device),
                adapter_names=[NAME_OF_ADAPTER]   # MUST PASS THIS IN
            )
```
