### ISSUE TITLE
For the task of translation, is it only applicable to model facebook/bart-base?

### ISSUE THREAD

**Issue by QzzIsCoding** [adapter-hub/adapter-transformers#261]
## Environment info

     
- `adapter-transformers` version:
- Platform: Ubuntu
- Python version: 3.7
- PyTorch version (GPU?): 1.10.0 with gpu

## Details
`export TASK_NAME=mrpc`
`python /examples/translation/run_translation.py \`
  `--model_name_or_path Helsinki-NLP/opus-mt-en-zh \`
  `--do_train \`
  `--do_eval \`
  `--source_lang en \`
  `--target_lang zh \`
`  --dataset_name /data/thesis \`
`  --dataset_config_name en-zh \`
`  --per_device_train_batch_size=32 \`
`  --per_device_eval_batch_size=4 \`
`  --learning_rate=1e-4 \`
`  --num_train_epochs=10.0 \`
`  --output_dir /share/qzz/en2zh/models/$TASK_NAME \`
`  --overwrite_output_dir \`
`  --train_adapter \`
`  --adapter_config=houlsby`

AttributeError: 'MarianConfig' object has no attribute 'adapters'

**Comment by calpt** [comment]
Hi,

yes, unfortunately, we currently don't support MarianMT. Supported models applicable to translation are BART, mBART and T5.

**Comment by BrightXiaoHan** [comment]
Hi @calpt. 
Is it possible to support FSMT model, which is very similar with BART and mBart.
