### ISSUE TITLE
How to add adapters only between decoder layers for Bart?

### ISSUE THREAD

**Issue by Eurus-W** [Adapter-Hub/adapter-transformers#264]
## Environment info

     
- `adapter-transformers` version:2.2.0
- Platform:Ubuntu 18.04.4 LTS (GNU/Linux 5.4.0-87-generic x86_64)
- Python version:Python 3.7.12
- PyTorch version (GPU?):1.10.1+cu113

## Details
Thanks to your briliant work,  I can add adapters to BartModel easily, but I have a problem now. I try to use adapter-transformers to load a BartModelWithHeads model and add a seq2seq2_lm head, then add a adapter and only train the adapter. But I want to only add the adapter modules between the decoder layers rather than every layers. I try to understand adapter Config and find nothing about that, **so is there a method to control the adding place/position of adapters modules or just delete the some adapters modules but not influence other process in adapters training?**

**Comment by hSterz** [comment]
Hey, you can use the `leave_out` parameter of the AdapterConfig to achieve this. The `leave_out` parameter specifies in which layers no adapter module should be added. You can simply pass a list of the indices of all encoder layers and then they do not have an adapter module. I hope this helps.

**Comment by Eurus-W** [comment]
> Hey, you can use the `leave_out` parameter of the AdapterConfig to achieve this. The `leave_out` parameter specifies in which layers no adapter module should be added. You can simply pass a list of the indices of all encoder layers and then they do not have an adapter module. I hope this helps.

Get it! Thanks for your generous reply!!! That is very helpful to me!!!!!

**Comment by insomnia1996** [comment]
> Hey, you can use the `leave_out` parameter of the AdapterConfig to achieve this. The `leave_out` parameter specifies in which layers no adapter module should be added. You can simply pass a list of the indices of all encoder layers and then they do not have an adapter module. I hope this helps.

Hi, I'm confused about the documentation of `leave_out`: `The IDs of the layers (starting at 0)`. Could you please explain how to rank the indices of all the layers? Taking 12-layer BART for an example, are encoder layers numbered from 0 to 11 and encoder layers 12-23? Thanks in advance!
