### ISSUE TITLE
Automatically determine whether we train adapters in Trainer

### ISSUE THREAD

**Issue by arueckle** [Adapter-Hub/adapter-transformers#27]
# 🚀 Feature request

Currently we need to manually pass `is_training_adapter` to the `Trainer`. 
See: https://github.com/Adapter-Hub/adapter-transformers/blob/d24649cea108baa2f33c4f3ac9c040b88a43abc0/src/transformers/trainer.py#L180

I did not know about this option and wondered why my script never exported adapters. Further, this only has an effect on checkpointing, not on the training. So we might want to rename it. Or better: automatically determine whether to export adapters or the full model.

**Comment by calpt** [comment]
@arueckle I assume you already implemented what you described here in 91a80a1b4bb31ef9909a1bae37f682cb335e75b4 and we can close this issue?

**Comment by arueckle** [comment]
It is not exactly what I envisioned earlier. Maybe even better because the current approach gives us more freedom. I initially though of reading whether we have some `active_adapters` and depending on that store only the adapters, fusion, or the full model. But it might interfere with setups in which we want to train the full model and adapters jointly.
