### ISSUE TITLE
About using both Fusion and Stack

### ISSUE THREAD

**Issue by ahtamjan** [adapter-hub/adapter-transformers#270]
Hello, I try to implement a cross-lingual transfer model. What I want is:
1. the output of  2 language adapters lan_a and lan_b be fused and then input to a classification adapter.
2. all of the 2 language adapters and classdification task adapter can be trained

I don't know which one I need to use,  train_adapter_fusion or train_adapter,and how to use.
Here is my codes:

    lang_adapter_config = AdapterConfig.load("pfeiffer", reduction_factor=8)
    model.load_adapter("en", config=lang_adapter_config, model_name = 'xlm-roberta-base')
    model.load_adapter("de", config=lang_adapter_config, model_name = 'xlm-roberta-base')

    model.add_adapter_fusion(["en", "de"])
    model.add_adapter("task")
    model.add_classification_head("task", num_labels=2)

    model.active_adapters = Stack(Fuse("en", "de"), "task")
    model.train_adapter_fusion(Stack(Fuse("en","de"), "task"))

**Comment by ajesujoba** [comment]
Hi @calpt, sorry I have been bothering you in recent time. 

I am also trying to do a similar thing: `I was to fuse 2 adapters and then stack the fused adapters on the task adapter. During training, I just want to train the fusion layer, the task adapter, and the task head. `

Below is my code snippet:
```
from transformers import AutoAdapterModel
from transformers import AdapterConfig
from transformers.adapters.composition import Fuse, Stack

# Load model
model = AutoAdapterModel.from_pretrained("xlm-roberta-base")
model.load_adapter("en/wiki@ukp", with_head=False)
model.load_adapter("de/wiki@ukp", with_head=False)

fusion_adapters = ['en','de']
model.add_adapter_fusion(fusion_adapters)
model.add_adapter("task")
model.add_classification_head("task", num_labels=4)
model.train_adapter_fusion(Stack(Fuse("en","de"), "task"))
```

However, the above snippet only trains the fusion and the task head without the task adapter. In addition, I tried the following:
```
model.apply_to_adapter_layers(lambda i, layer: layer.enable_adapters(Stack(Fuse("en","de"), "task"), True, True))
```

Does adapter-transformer support what I am trying to do? What would suggest I do? Unfreeze the task adapters separately.

**Comment by VarunGumma** [comment]
Any leads on this? Were you able to do it? I am stuck on the same issue.

**Comment by VarunGumma** [comment]
@ajesujoba @ahtamjan @calpt, this could be a potential solution that works for me and for now:

```
for name, module in model.named_modules():
    for name_, param_ in module.named_parameters():
        param_.requires_grad = "task" in name or "adapter_fusion_layer" in name
            model.set_active_adapters(Stack(Fuse("en","de"), "task"))

model.set_active_adapters(Stack(Fuse("en","de"), "task"))
```
This only trains the fusion layer, task adapter, and classification head.
