### ISSUE TITLE
Adding model from HuggingFace to Adapter-hub without training

### ISSUE THREAD

**Issue by mobashgr** [adapter-hub/adapter-transformers#273]
Hi,
I was wondering if I can add a fine-tuned model from HuggingFace for token classification, for example, https://huggingface.co/ghadeermobasher/BC5CDR-Chemical-Disease-balanced-SapBERT-UMLS-2020AB-all-lang-from-XLMR to Adapterhub?  

I need to use this model to be added as an external recommender on INCEpTION and I realized the only way to do so in my case is via adapter-transformers.

A quick response is kindly appreciated. 

Best,
Ghadeer

**Comment by calpt** [comment]
Hi @mobashgr,

I'm not quite sure what you are trying to achieve. In principle, adapter-transformers is fully compatible to HuggingFace transformers, so you can just use the same commands as in transformers, i.e.:

```python
from transformers import AutoTokenizer, AutoModelForTokenClassification

tokenizer = AutoTokenizer.from_pretrained("ghadeermobasher/BC5CDR-Chemical-Disease-balanced-SapBERT-UMLS-2020AB-all-lang-from-XLMR")
model = AutoModelForTokenClassification.from_pretrained("ghadeermobasher/BC5CDR-Chemical-Disease-balanced-SapBERT-UMLS-2020AB-all-lang-from-XLMR")
```

Now you might add an adapter using:
```python
model.add_adapter("adapter_name")
```

**Comment by mobashgr** [comment]
Hi @calpt ,
Thanks for your reply.
I have tried adding `model.add_adapter("adapter_name")` and I got this error as shown in the picture. 
![image](https://user-images.githubusercontent.com/53903145/151001016-c1199f08-786c-4ccc-b245-16a8ea3abd53.png)
I want to use my fine-tuned model as an external recommender on INCEpTION. I have figured out that the only way to do it is via  [Adapters](https://github.com/inception-project/inception-external-recommender/blob/master/ariadne/contrib/adapters.py).
So I need to add this model to Adapterhub to be able to use it for INCEpTION. I hope it is clear now.

**Comment by Darshan2104** [comment]
Hey @mobashgr,
Look I tried the same thing- loading finetuned model and adding an adapter on it- for the summarization task and it worked!
 What I did is,
```
model = AutoModel.from_pretrained('/content/drive/MyDrive/t5-small-cnn')
adapter_name = model.load_adapter("@ukp/facebook-bart-large_sum_cnn_dailymail_pfeiffer", source="ah" model_name="bart-large")
model.save_pretrained('my-T5-small')
```
you can check it by 
`model.config`

Correct me if I'm going wrong somewhere. 
:)

**Comment by linqian66** [comment]
Maybe you did not install AdapterHub (adapter-transformers) properly, better start with a new environment without existing transformers package (see https://docs.adapterhub.ml/installation.html).
