### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by Darshan2104** [adapter-hub/adapter-transformers#276]
## Details
Hey there,
I've been working with an adapter recently (~2 weeks). I have one confusion with this [run_summarization.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/summarization/run_summarization.py) file (line - 457).

In this, they have mentioned that "Adapter can only be loaded in training mode" my question is why?
What if I only want to load what already exists in the adapter-hugging face? 

am I missing something or what?

**Comment by calpt** [comment]
I agree that the error message on this might be a bit confusing: This doesn't mean that it is only possible to train new adapters. Rather, it means that you always have to pass `--train_adapter` when using adapters. You can very well load existing adapters with `--load_adapter` and evaluate them (by only passing `--do_eval` to the script)
