### ISSUE TITLE
Training stack of  adapter together

### ISSUE THREAD

**Issue by ffaisal93** [Adapter-Hub/adapter-transformers#278]
Hello,
If I have a stack of language adapters to train: stack(AdaptorA, AdaptorB)

Is it possible to train this stack in one setting and save both the adapter checkpoints in one run?

Thanks!

**Comment by hSterz** [comment]
Hello, 
As I understand it, you want to train a stack of adapters while freezing the weights of the remaining model.
If that is the case, you can achieve that by calling: `model.train_adapter(["adapter1", "adapter2"])` and then training your model like you normally would.  After training, you can either save the adapters individually or call `save_all_adapters`.
I hope this helps.
