### ISSUE TITLE
When will the next version be released?

### ISSUE THREAD

**Issue by cody-moveworks** [Adapter-Hub/adapter-transformers#279]
Hi there! I'm wondering when the next planned version release is? The last release version was in October, and the latest transformers version (currently 4.16.2) has fixes for some models that would be useful to have in adapter-transformers as well.

**Comment by cody-moveworks** [comment]
Gentle bump cc @calpt :)

**Comment by JoPfeiff** [comment]
Hey @cody-moveworks,
thanks for the request! We are heavily in the works of releasing a new version within the next 2-3 weeks!
We have some sweet new treats in the pipeline which we want to include as well and are currently testing their performance!

**Comment by cody-moveworks** [comment]
Awesome! Thank you for the update @JoPfeiff! Looking forward to the next release :)

**Comment by calpt** [comment]
Closing, as v3 with upgrade to latest Transformers version is now released :)
