### ISSUE TITLE
How to add new head?

### ISSUE THREAD

**Issue by fer-git** [adapter-hub/adapter-transformers#280]
I can see plenty implementation of heads for many NLP tasks in [here](https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapters/heads/base.py).

What is the way to create my own custom head for other NLP task? Should the code be forked?

**Comment by hSterz** [comment]
Hey, 
we actually provide methods for adding a custom head. You can start by defining a custom head similarly to the following template:
```python 
class CustomHead(PredictionHead):
    def __init__(
        self,
        model, # reference to the model the head is added to
        head_name, # the name of the head that is created
        **kwargs,
    ):
        # innitialization of the custom head

    def forward(self, outputs, cls_output=None, attention_mask=None, return_dict=False, **kwargs):
        # implementation of the forward pass
```

Then, you can register your custom head to the model:
```python
model.register_custom_head("my_custom_head", CustomHead)
```
This does not add a head yet, it only registers the new custom head so you can add it as follows:
```python
model.add_custom_head(head_type="my_custom_head", head_name="my_new_head", **kwargs)
```
After adding the head, it behaves like the build-in heads.

I hope this helps.
