### ISSUE TITLE
Translation between adapters

### ISSUE THREAD

**Issue by ramitsurana** [adapter-hub/adapter-transformers#286]
## Environment info

     
- `adapter-transformers` version:
- Platform: Google Collab
- Python version: v3.7
- PyTorch version (GPU?): GPU

## Details
Hi, I have trained a model using language adapters with a Stack structure. For testing purposes, I want to test the translation between these 2 languages and was looking for any sample code for the reference. Can you please suggest any sample references on the same?

Thanks

**Comment by lavine-lmu** [comment]
The language adapters we trained are based on ```encoder``` framework. but the translation task is a ```encoder-decoder``` task. so I think it is difficult to use language adapter pre-trained in ```Adapterhub```. Right?

**Comment by ramitsurana** [comment]
True, but I think it should be possible, ref - https://github.com/Adapter-Hub/adapter-transformers/blob/master/notebooks/04_Cross_Lingual_Transfer.ipynb. Unfortunately, this example only demonstrated on how to load and train 2 adapters but not on how to do the translation.

**Comment by JoPfeiff** [comment]
The language adapters currently available on the adapterhub are training using MLM, so cannot be used for MT out-of-the-box. It would be interesting though, what would happen if you re-use them in a seq2seq setup (e.g. using mBERT-mBERT setup), but I am pretty sure that you would need to align them to some extent on multilingual sentence-pairs in a standard MT setup. 
This has not been investigated yet afaik.

**Comment by ramitsurana** [comment]
Thanks @JoPfeiff and @lavine-lmu .
