### ISSUE TITLE
why the default setting contains 3 pre-trained layernorm?

### ISSUE THREAD

**Issue by Tsingularity** [Adapter-Hub/adapter-transformers#290]
Hi, thanks for the great work!

In the AdapterFusion and the AdaperHub paper, the default configuration contains 3 pre-trained LayerNorm (as in figure 3 of AdapterHub). However, if I understand correctly, the default transformer block only contains 2 layernorm (as in figure 1 of "attention is all u need")? So I am just wondering, how should I initialize the new layernorm and whether I should set it to trainable or not?

Thanks!

**Comment by calpt** [comment]
Hey @Tsingularity, what is shown in the adapter architecture figures are the options where layer norms _can be_ placed within a Transformer layer. Usually, only, one layer norm is used per sub-layer (attention, FFN) either before or after the adapter layer, same as in the original Transformer. Where a layer norm is placed depends on the adapter configuration used. You can specify the layer norms used with the [`AdapterConfig`](https://docs.adapterhub.ml/classes/adapter_config.html#transformers.AdapterConfig) class. [This figure](https://docs.adapterhub.ml/_images/architecture.png) additionally visualizes the mapping from config keys to Transformer layer components.
In adapter-transformers, the pre-trained layer norm is typically kept fixed. However, you can also add a newly initialized layer norm within the adapter layer (see figure and config class).

**Comment by Tsingularity** [comment]
thanks!
