### ISSUE TITLE
New model: CLIP

### ISSUE THREAD

**Issue by NotNANtoN** [adapter-hub/adapter-transformers#296]
# 🌟 New adapter setup
Hi, in my Master thesis I am currently working with fine-tuning CLIP on specific image-text datasets. Concretely, I am using the MIMIC-CXR dataset (https://physionet.org/content/mimic-cxr/2.0.0/).I'm training Adapters for the model and therefore I thought of possibly uploading them to AdapterHub! I think it would be a great addition to have the CLIP model available too, as we could then extend it as a community.

The main point would be to add the model architecture of the OpenAI CLIP model from here: https://github.com/openai/CLIP/blob/main/clip/model.py
I added adapters to the ResidualAttentionBlock.

So I'm basically asking: is there interest for this model? If so, I would gladly try to contribute this, but I might need some help as I am not super familiar with AdapterHub yet. If there are some instructions of how I could best add a new model that would be amazing.

**Comment by calpt** [comment]
Hey @NotNANtoN,

We're always very interested in contributions of new models, so we would be very happy to have your contribution!

Some initial pointers:
- To get started with implementing a new model integration, we have a small guide on the general procedure: https://github.com/Adapter-Hub/adapter-transformers/blob/master/adding_adapters_to_a_model.md.
- To get some more context on the integration in general, you might also refer to our documentation on this: https://docs.adapterhub.ml/model_overview.html.
- When starting the implementation, please make sure to use the latest version of the `master` branch.

We're happy to help in case you have any questions/ issues!
