### ISSUE TITLE
clarity on fusion interface

### ISSUE THREAD

**Issue by ianupright** [Adapter-Hub/adapter-transformers#303]
Lets say you have two adapters, rte and mnli.  Now you want to train rte and fusion together, using mnli as a frozen adapter.

What is the correct protocol to achieve this?  Something like this?

model.train_adapter(['rte'])
fusion_adapters = ['rte','mnli']
fusion = ac.Fuse(fusion_adapters)
model.add_adapter_fusion(fusion)
model.set_active_adapters(fusion)

also, not sure it matters, but on the latest development branch

**Comment by calpt** [comment]
As I understand, you would like train both the fusion layer and the RTE adapter. If this is the case, the steps to achieve look a bit different:
First, add and activate AdapterFusion for training:
```python
fusion_adapters = ['rte','mnli']
fusion = Fuse(fusion_adapters)
model.add_adapter_fusion(fusion)
model.train_adapter_fusion(fusion)
```
Note that `train_adapter_fusion()` _only_ "unfreezes" the fusion layer, but not the adapters. Thus, we have to activate the rte adapters separately. As `train_adapter()` would change the activated setup, you can use a small trick:
```python
model.apply_to_adapter_layers(lambda i, layer: layer.enable_adapters(Stack("rte"), True, False))
```
Now, the fusion layer and the rte adapter are activated for training, while the mnli is kept frozen.

Hope this helps!
