### ISSUE TITLE
reduction_factor as a float

### ISSUE THREAD

**Issue by ianupright** [adapter-hub/adapter-transformers#306]
it would be useful if the reduction_factor was simply a float..
int(hidden_size/reduction_factor)
For example, you currently can't specify a reduction factor of 1.5 or 2.5
I have experimented with some of my own proprietary models yielding an optimum with a reduction factor of 2. (as opposed to 1 or 3)
Values of less than one could expand, which I would think would be unusually beneficial.

**Comment by calpt** [comment]
Yes, this totally makes sense. In case you already implemented and experimented with the change, I'd be happy for a PR from your side (please use the develop branch as base). Otherwise, we'll look into it.
