### ISSUE TITLE
Getting specific adapter layer weights

### ISSUE THREAD

**Issue by ffaisal93** [adapter-hub/adapter-transformers#308]
Hello,
Hope you are doing well.

My question is, how I can use the weights from a specific adapter layer.

for example,
```
model.add_adapter("a")
model.add_adapter("b")
model.add_adapter("c")

model.active_adapters = ac.Stack("a", "b", "c")
```

Now,
```
output = model(**inputs, output_hidden)  # should give the output: loss and hidden states
```

from this output['hidden_state'] or anything else, how I can get the parameters/layer embedding weights specific to certain adapters (adapter a, b and c)?

Thanks

**Comment by calpt** [comment]
Hey @ffaisal93,

You can access the weights of a specific adapter using the [`get_adapter()`](https://docs.adapterhub.ml/classes/model_mixins.html#transformers.ModelAdaptersMixin.get_adapter) method, e.g.:

```python
model.add_adapter("a")

params = model.get_adapter("a")
print(params)
```
