### ISSUE TITLE
how does reduction-factor work?

### ISSUE THREAD

**Issue by Jiang-X-Pro** [Adapter-Hub/adapter-transformers#312]
hi, i'm new to the adapter-transformers and i  wonder how does the reduction-factor work? Could you please give some information like paper or blog?

**Comment by Jiang-X-Pro** [comment]
I'm also curious about the difference between train_adapter() and set_active_adapters(), what should I do if I want to train parameters of adapter and  bert at the same time?

**Comment by hSterz** [comment]
Hey, 
the reduction-factor describes the ratio between the layer's hidden dimension and the bottleneck dimension. Feel free to checkout [our documentation](https://docs.adapterhub.ml/overview.html#bottleneck-adapters) on bottleneck adapters. There we also explain this.

The `set_active_adapters()` method activates the given adapter setup, such that it is used for each forward pass. The `train_adapters()` method activates the adapter and additionally freezes the weights of the transformer so only the adapter weights are adapted during training. So if you want to train both the adapter and bert you can call only `set_active_adapters()` then the bert weights and the adapter weights should be updated during training.

I hope this helps.

**Comment by Jiang-X-Pro** [comment]
Thanks for your quick and helpful response
