### ISSUE TITLE
Can we correctly use AdapterFusion for mBART?

### ISSUE THREAD

**Issue by thisaltennakoon** [adapter-hub/adapter-transformers#313]
I am trying to use AdapterFusion to fuse some adapters when having mBART as the core. But after adding AdapterFusion using model.add_adapter_fusion(adapter_setup[0]), it has added a BertFusion component as follows.

(layers): ModuleList(
        (0): MBartEncoderLayer(
          (self_attn): MBartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (attention_adapters): BartSelfAttentionAdaptersModule(
            (adapters): ModuleDict(
              (si_ta): Adapter(
                (non_linearity): Activation_Function_Class()
                (adapter_down): Sequential(
                  (0): Linear(in_features=1024, out_features=512, bias=True)
                  (1): Activation_Function_Class()
                )
                (adapter_up): Linear(in_features=512, out_features=1024, bias=True)
              )
              (en_ta): Adapter(
                (non_linearity): Activation_Function_Class()
                (adapter_down): Sequential(
                  (0): Linear(in_features=1024, out_features=512, bias=True)
                  (1): Activation_Function_Class()
                )
                (adapter_up): Linear(in_features=512, out_features=1024, bias=True)
              )
            )
            (adapter_fusion_layer): ModuleDict(
              (si_ta,en_ta): BertFusion(
                (dropout): Dropout(p=0.0, inplace=False)
                (query): Linear(in_features=1024, out_features=1024, bias=True)
                (key): Linear(in_features=1024, out_features=1024, bias=True)
                (value): Linear(in_features=1024, out_features=1024, bias=False)
              )
            )
          )
          (output_adapters): BartOutputAdaptersModule(
            (adapters): ModuleDict(
              (si_ta): Adapter(
                (non_linearity): Activation_Function_Class()
                (adapter_down): Sequential(
                  (0): Linear(in_features=1024, out_features=512, bias=True)
                  (1): Activation_Function_Class()
                )
                (adapter_up): Linear(in_features=512, out_features=1024, bias=True)
              )
              (en_ta): Adapter(
                (non_linearity): Activation_Function_Class()
                (adapter_down): Sequential(
                  (0): Linear(in_features=1024, out_features=512, bias=True)
                  (1): Activation_Function_Class()
                )
                (adapter_up): Linear(in_features=512, out_features=1024, bias=True)
              )
            )
            (adapter_fusion_layer): ModuleDict(
              (si_ta,en_ta): BertFusion(
                (dropout): Dropout(p=0.0, inplace=False)
                (query): Linear(in_features=1024, out_features=1024, bias=True)
                (key): Linear(in_features=1024, out_features=1024, bias=True)
                (value): Linear(in_features=1024, out_features=1024, bias=False)
              )
            )
          )
        )

**Is this correct? 
Is 'BertFusion' just a name?**

**Comment by calpt** [comment]
Hi @thisaltennakoon, this is expected. `BertFusion` is just the name of the module, it works with any of the supported model classes.

**Comment by thisaltennakoon** [comment]
Thank You
