### ISSUE TITLE
Confusing Data-Field name on Web-Page

### ISSUE THREAD

**Issue by Darshan2104** [Adapter-Hub/adapter-transformers#315]
Hello Huggingface team,

In Dataset **GEM/xlsum** Data-field : **summary** is confusing!!! [link](https://huggingface.co/datasets/GEM/xlsum#data-fields)

While loading data **Target** is used as a label instead of **summary**. 
**Summary** on [link](https://huggingface.co/datasets/GEM/xlsum#data-fields) is confusing and misguiding.

Hope you find this useful and try to update it asap.

Thanks :)

**Concern** : could you just add the help/bug module on the Huggingface website with a helping mail-id that can help people to contact you easily to solve this kind of issue!!!

**Comment by hSterz** [comment]
Hello, 
we are not the huggingface team. We only provide the support for the adapters-transformers library which is based on huggingface transformers. Hence, this issue probably belongs in the [huggingface/transformers repository](https://github.com/huggingface/transformers).
