### ISSUE TITLE
What exactly does `set_active_adapters` do?

### ISSUE THREAD

**Issue by seongminp** [Adapter-Hub/adapter-transformers#318]
Hello. 

Thanks for this wonderful library.

From the AdapterHub website:

> The weights of this classification head can be stored together with the adapter weights to allow for a full reproducibility. The method call model.set_active_adapters("sst-2") registers the sst-2 adapter as a default for training. This also supports adapter stacking and adapter fusion!
 
I did not understand what "registers as a default for training" exactly means. What does `set_active_adapters` do that is not achieved by `add_adapter` and `train_adapter`? 

Thanks!

**Comment by hSterz** [comment]
Hey,
the `add_adapter` method only adds the adapter to the model. If you then call `model(input_ids)` the added adapter is not used during the forward pass. To use that adapter in the forward pass, you need to call `set_active_adapters`. 
The `train_adapter` method freezes the weights of the pretrained model, such that only the adapter weights are adapted during training. It also calls the `set_active_adapters` method. So if you use `train_adapter` you don't have to call the `set_active_adapters`.
I hope this helps.

**Comment by seongminp** [comment]
Thanks for the detailed answer! I'll close the issue.
