### ISSUE TITLE
How to freeze all the adapters and just fine-tune the parameters of BERT?

### ISSUE THREAD

**Issue by leopoldwhite** [Adapter-Hub/adapter-transformers#326]
I want to further fine-tune the BERT  after I get the pretrained adapters , which means I want to fine-tune BERT without changing any parameters in adapters. Is there any way to achieve this goal?

**Comment by calpt** [comment]
Hey @leopoldwhite,

While there is no built-in function to achieve exactly this, you might iterate through the weights of an adapter to freeze it weights, e.g.:
```python
model.add_adapter("test_adapter")

# Makes sure to unfreeze all model weights
model.freeze_model(False)

for _, d in model.get_adapter("test_adapter").items():
    for _, module in d.items():
        for param in module.parameters():
            param.requires_grad = False
```

**Comment by leopoldwhite** [comment]
> Hey @leopoldwhite,
> 
> While there is no built-in function to achieve exactly this, you might iterate through the weights of an adapter to freeze its weights, e.g.:
> 
> ```python
> model.add_adapter("test_adapter")
> 
> # Makes sure to unfreeze all model weights
> model.freeze_model(False)
> 
> for _, d in model.get_adapter("test_adapter").items():
>     for _, module in d.items():
>         for param in module.parameters():
>             param.requires_grad = False
> ```

Thank you so much , my problem is perfectly solved by your proposal.
