### ISSUE TITLE
Directly editing adapter values

### ISSUE THREAD

**Issue by alu13** [adapter-hub/adapter-transformers#329]
Hi, is there a way to directly replace/change adapter values with a new set of values, like a set_adapter function?

**Comment by calpt** [comment]
Hey @alu13,

While there is no set_adapter function, you can access the weights of an adapter using the `get_adapter()` method:
```python
for layer_id, d in model.get_adapter("test_adapter").items():
    for location, module in d.items():
        # "module" is a standard PyTorch module ...
        for n, p in module.named_parameters():
            print(n, p)
```
