### ISSUE TITLE
Input data passed as "inputs_embeds" instead of "input_ids", model crashes

### ISSUE THREAD

**Issue by odytokoumbo** [adapter-hub/adapter-transformers#333]
## Information
I am trying to train a pretrained gpt2 model with a simple adapter and instead of the standard "input_ids" parameter I pass "inputs_embeds". I tried this with the original gpt2 pretrained from huggingface and it works perfectly. However, although I don't try to train an adapter with Prefix Tuning, my model crashes on "prefix_state" parameter of Prefix Tuning, because I don't use "input_ids" as my input data, but "inputs_embeds".

Model I am using (Bert, XLNet ...): GPT2

Language I am using the model on (English, Chinese ...): My own trained embeddings passed on "inputs_embeds"

Adapter setup I am using (if any): Houlsby

My model setup:
```python
model = AutoAdapterModel.from_pretrained("gpt2")
model.add_classification_head(adapter_name, num_labels=n_classes)
config = transformers.HoulsbyConfig()
model.add_adapter(adapter_name, config)
model.set_active_adapters(adapter_name)
model.train_adapter(adapter_name)
............................................................................
output = model(input_embeds=x, return_dict=True).last_hidden_state
```

```
Error Message:  
/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
/transformers/adapters/models/gpt2.py", line 61, in forward
    outputs = self.transformer(
  File "/transformers/adapters/context.py", line 95, in wrapper_func
    with cls(self, *args, **kwargs):
  File "/transformers/adapters/context.py", line 77, in __init__
    model.forward_context(self, *args, **kwargs)
  File "/transformers/adapters/model_mixin.py", line 619, in forward_context
    context.prefix_states = self.base_model.prefix_tuning(input_tensor.shape[0])
AttributeError: 'NoneType' object has no attribute 'shape'
```

lines 619 and above in forward_context

```python
# Prefix tuning
input_tensor = kwargs.get("input_ids", None)
if input_tensor is None:
    input_tensor = kwargs.get("decoder_input_ids", None)
if input_tensor is None:
    input_tensor = kwargs.get("attention_mask", None)
if input_tensor is None:
    input_tensor = args[0]
context.prefix_states = self.base_model.prefix_tuning(input_tensor.shape[0])
```
## Expected behavior
If I understand the code correctly "prefix_states" should only be computed if "input_tensor" is not None (else at least a comprehensible error should be printed). Also, I claim that prefix_states should only be computed if prefix tuning is needed as the config requires.

###Disclaimer
Thanks a lot for your efforts. I hope my issue is clear and I haven't made a silly mistake.

**Comment by calpt** [comment]
Hey @odytokoumbo, thanks for reporting this. This is indeed an issue with our implementation. Should be fixed by #335.
