### ISSUE TITLE
Using Adapters for Machine Translation

### ISSUE THREAD

**Issue by salma-elshafey** [adapter-hub/adapter-transformers#350]
I am trying to use adapters for machine translation from Arabic to English. I use pre-trained AraBERT, a BERT model trained on the Arabic language. However I keep getting an error message. I'd be extremely grateful if you could help with this problem or provide a guide on how exactly to use adapters on BERT models for Machine Translation.

##My code:
`model.add_adapter("ar_en_translation")
model.train_adapter("ar_en_translation")

training_args = TrainingArguments(
    learning_rate=1e-4,
    num_train_epochs=6,
    logging_steps=200,
    output_dir="drive/MyDrive/training_output",
    overwrite_output_dir=True,
    evaluation_strategy = "epoch",
    remove_unused_columns=False,
)

trainer = AdapterTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics,
)

trainer.train()`

##The error message
`/usr/local/lib/python3.7/dist-packages/transformers/data/data_collator.py in torch_default_data_collator(features)
    128                 batch[k] = torch.stack([f[k] for f in features])
    129             else:
--> 130                 batch[k] = torch.tensor([f[k] for f in features])
    131 
    132     return batch

ValueError: expected sequence of length 12 at dim 1 (got 148)`

**Comment by adapter-hub-bert** [comment]
This issue was closed because it was stale for 14 days without any activity.
