### ISSUE TITLE
Adapter layers over a pre-existing classifier

### ISSUE THREAD

**Issue by raunak-agarwal** [adapter-hub/adapter-transformers#352]
Is it possible to add adapter layers on top of a pre-existing classifier such as [this NLI model](https://huggingface.co/cross-encoder/nli-deberta-v3-large)? The goal here is to avoid catastrophic forgetting if we want to finetune the NLI model on new data.

**Comment by adapter-hub-bert** [comment]
This issue was closed because it was stale for 14 days without any activity.
