### ISSUE TITLE
How come vanilla finetuning of bert with ~ 100x more trainable parameters compared to bert + adapter takes just 2x time?

### ISSUE THREAD

**Issue by macabdul9** [adapter-hub/adapter-transformers#360]
## Environment info
- `adapter-transformers` version: 3.0.1
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- PyTorch version (GPU?): 1.11.0+cu113 (True)
- Tensorflow version (GPU?): 2.8.2 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?:Yes
- Using distributed or parallel set-up in script?: No

## Details
Finetuning bert model on imdb dataset takes ~20mins/epoch while bert finetuning with adapter takes ~12mins/epoch. The first case has 109M trainable parameters and the bert+adapter has less than 2M trainable parameters. 

None

**Comment by adapter-hub-bert** [comment]
This issue was closed because it was stale for 14 days without any activity.
