### ISSUE TITLE
Model does not contain a head with name xxx, but I really don't want a head

### ISSUE THREAD

**Issue by ZeguanXiao** [adapter-hub/adapter-transformers#369]
## Environment info

     
- `adapter-transformers` version:3.0.1
- Platform:Ubuntu 18.04
- Python version:3.8.10
- PyTorch version (GPU?):GPU

## Details
I want the stacked adapter output hidden states and use them as encoder memory and output to decoder. How can I do this? 
error always raise: Model does not contain a head with name xxxx
```
self.encoder = AutoAdapterModel.from_pretrained(model_name_or_path)
lang_adapter_config = AdapterConfig.load("pfeiffer", non_linearity="relu", reduction_factor=2)
lang_adapter_name = self.encoder.load_adapter(adapter_name_or_path, config=lang_adapter_config)
task_adapter_config = AdapterConfig.load("pfeiffer", non_linearity="relu", reduction_factor=2)
self.encoder.add_adapter("dg_task_adapter", config=task_adapter_config)
self.encoder.active_adapters = composition.Stack(lang_adapter_name, "dg_task_adapter")

```

**Comment by calpt** [comment]
Hey @ZeguanXiao, thanks for bringing this up. This is indeed an issue of our implementation, the model should not attempt to activate a prediction head if none is added. Should be resolved by #377.
