### ISSUE TITLE
How to use a K-adapter

### ISSUE THREAD

**Issue by debby1103** [adapter-hub/adapter-transformers#374]
Is there any demo please?

**Comment by debby1103** [comment]
Is that available already? Thanks

**Comment by calpt** [comment]
Please have a look at the discussion in #274. Basically, we agreed there that there currrently is little additional benefit of adding K-Adapter to this library at the moment. However, we're open to discuss this again if there is more interest.

**Comment by calpt** [comment]
Closing this in favor of #274, please add additional comments over there. Thanks!
