### ISSUE TITLE
Trainer doesn't work with multi-gpu setup

### ISSUE THREAD

**Issue by prajjwal1** [Adapter-Hub/adapter-transformers#38]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): `bert-base-uncased`

Language I am using the model on (English, Chinese ...): English

Adapter setup I am using (if any): `Default`

The problem arises when using:
* [x] the official example scripts: (give details below): `run_glue_wh.py`
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name) MNLI
* [ ] my own task or dataset: (give details below)

## To reproduce

HF default `Trainer` wraps the model in `DataParallel` if `training_args.n_gpu` > 1. As a result, it doesn't have the `config` attribute. When I use your modified `Trainer`, I am getting the error,  `DataParallel object has no attribute 'config'`

## Expected behavior

It should not raise the above error.

## Environment info

     
Using the master version of this repo. I had to use `CUDA_VISIBLE_DEVICES` flag to specify one GPU.

**Comment by theorist17** [comment]
In such models, wrapped up in DataParallel, model.module.config might be right, instead of model.config.

**Comment by calpt** [comment]
@prajjwal1 Thanks for reporting. I think #51 should fix the specific issue you reported. Please check if this solves your issue.
