### ISSUE TITLE
Newer Huggingface Models Not Supported?

### ISSUE THREAD

**Issue by MultiTrickFox** [adapter-hub/adapter-transformers#392]
trying to import 'bigscience/bloom-2b5' as base model ;

from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained('bigscience/bloom-2b5')
-> error: KeyError: 'bloom'

from transformers import BloomForCausalLM
-> error: cannot import name 'BloomForCausalLM' from 'transformers'

Bloom is fairly a newer model, is not released on adapter-hub yet? I thought your repo would sync automatically with HF's. Or am I missing something here?

**Comment by RulinShao** [comment]
The adapterhub doesn't support automatic sync with huggingface (I also hope they could though). I think the current version only support the models in https://docs.adapterhub.ml/model_overview.html
And you could find the corresponding implementation in https://github.com/adapter-hub/adapter-transformers/tree/master/src/transformers/adapters/models
I guess if you need it in a hurry, you could follow these codes to add the new ones.

**Comment by MultiTrickFox** [comment]
Thank you..
