### ISSUE TITLE
How to use multiple prefix tuned models with parallel inference. 

### ISSUE THREAD

**Issue by santhoshkolloju** [adapter-hub/adapter-transformers#393]
Hi Library error when I use muliptle prefix tuned models for parallel inference. 
What are the adpaters which supports parallel inference and how to know their configuration. 

Thanks

**Comment by calpt** [comment]
Hey, parallel inference (as well as all other adapter composition blocks) are currently only supported with the "original" bottleneck adapter configuration (all adapters using `AdapterConfig`). Support for other methods such as prefix tuning may be added in the future.
