### ISSUE TITLE
documentation bug 

### ISSUE THREAD

**Issue by nabsabraham** [adapter-hub/adapter-transformers#395]
## Environment info

     
- `adapter-transformers` version: 3.0.1
- Platform: mac os
- Python version: 3.9.7
- PyTorch version (GPU?): 1.12.0
- Tensorflow version (GPU?):
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?: NO

## Information

Model I am using (Bert, XLNet ...):`BertAdapterModel`
Language I am using the model on (English, Chinese ...): English
Adapter setup I am using (if any):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce
```python
# https://docs.adapterhub.ml/quickstart.html
import torch
from transformers import BertTokenizer
from transformers.adapters import BertAdapterModel

# Load pre-trained BERT tokenizer from Huggingface.
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# An input sentence.
sentence = "It's also, clearly, great fun."

# Tokenize the input sentence and create a PyTorch input tensor.
input_data = tokenizer(sentence, return_tensors='pytorch')

# Load pre-trained BERT model from HuggingFace Hub.
# The `BertAdapterModel` class is specifically designed for working with adapters.
# It can be used with different prediction heads.
model = BertAdapterModel.from_pretrained('bert-base-uncased')
```

1. Run the above example script

## Expected behavior
Runs without error however, script errors with: 
```
ValueError: pytorch is not a valid TensorType, please select one of ['pt', 'tf', 'np', 'jax']
```

## Solution
Replace `return_type='pytorch'` with `return_type='pt'`

**Comment by calpt** [comment]
Thanks for reporting :)
