### ISSUE TITLE
Any plan for the next release?

### ISSUE THREAD

**Issue by jingtaozhan** [adapter-hub/adapter-transformers#403]
This is a wonderful project. It helps me a lot!
The project I'm going to open source depends on the recently added features of adapter-transformer (LoRA). Will there be an official release in the near future so I can just pip install it instead of installing it from the source code? 
Thank you!

**Comment by calpt** [comment]
Hey @jingtaozhan, glad to hear that this project is useful to you. We're planning to release a new version on PyPI in the next 1 or 2 weeks, as soon as some reamining changes are merged (e.g. #396) and the library is updated to the latest HF Transformers version.

**Comment by jingtaozhan** [comment]
Glad to hear that. Great Job!
