### ISSUE TITLE
ImportError: cannot import name 'AutoAdapterModel' from 'transformers'

### ISSUE THREAD

**Issue by SongYuQiu** [adapter-hub/adapter-transformers#415]
## Environment info

     
- `adapter-transformers` version: 3.1.0a1
- Platform: Linux-5.4.0-124-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.13
- PyTorch version (GPU?): not installed (NA)

## Details

Hello, I want to run the code of MAD-X. When executing Task Adapter Training, I encountered this error and have not been able to find a solution. Hope to get your help, thank you.

**Comment by ryanyhliu** [comment]
Hello, how u solved that?
