### ISSUE TITLE
Loading MAM adapters to fusion layer

### ISSUE THREAD

**Issue by ujo142** [adapter-hub/adapter-transformers#416]
Hi, 

I would like to ask how exactly should be adapters loaded via "add_adapter_fusion()" method with MAM config? When i pass inside Fuse("adapter1_name", "adapter2_name") i get error "not enough values to unpack (expected 2, got 1)". As far as i understand the "add_adapter_fusion" requires two elements which refers to prefixTuning and Parallel  config. But how exactly pass It correctly?

**Comment by calpt** [comment]
Hi @ujo142, unfortunately, MAM adapters currently don't support adapter compositions such as AdapterFusion. Currently, you can only use AdapterFusion with bottleneck adapters such as `PfeifferConfig()` or `HoulsbyConfig()`. We're considering to expand the support for composition blocks in the future.

**Comment by adapter-hub-bert** [comment]
This issue was closed because it was stale for 14 days without any activity.
