### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'device_map'

### ISSUE THREAD

**Issue by Joonsun-Hwang** [adapter-hub/adapter-transformers#419]
```
model = AutoModelForCausalLM.from_pretrained(
                args.pretrained_model,
                revision=args.revision,
                device_map=args.device_map,
                low_cpu_mem_usage=True,
                cache_dir=os.environ['TRANSFORMERS_CACHE'])
```

If I load and use the model as above, the model will load well if I use the transformers library only. However, if I run adapter-transformers after installing it, it seems that device_map among the arguments is not supported.

And when I load the facebook/opt kind of model, the KeyError occurs in the tokenizer.

**Comment by calpt** [comment]
This issue is likely caused by the adapter-transformers version you're using being based on an older version of transformers that doesn't support the `device_map` parameter yet. It should be solved by using the latest release (v3.1.0) or the latest version of the master branch of this repo.
