### ISSUE TITLE
How to add adapter to T5EncoderModel?

### ISSUE THREAD

**Issue by ChengJiacheng** [adapter-hub/adapter-transformers#427]
## Environment info

     
- `adapter-transformers` version: 3.1.0
- Platform: Linux 
- Python version: 3.10
- PyTorch version (GPU?): 1.12.1

## Details
Hi, thank you so much for the great work! 
I am trying to add adapter to T5 encoder as below. However, it seems not to work. There is no adapters added in the model and `t5encoder.get_adapter("bottleneck_adapter")` gives me an empty list. Did I miss anything? Any hints or suggestion would be greatly appreciated. Thanks!

```
from transformers import T5EncoderModel, T5Tokenizer
from transformers.adapters import BertAdapterModel, AdapterConfig

model_name_or_path = 't5-base'
t5encoder = T5EncoderModel.from_pretrained(model_name_or_path)

adapter_config = AdapterConfig(mh_adapter=True, output_adapter=True, reduction_factor=2, non_linearity="relu")
t5encoder.add_adapter("bottleneck_adapter", config=adapter_config, set_active=True)
```

**Comment by calpt** [comment]
Hey @ChengJiacheng, thanks for bringing this up! What you describe does seem to be a bug in our current implementation. We'll fix that shortly.

**Comment by ra-MANUJ-an** [comment]
Hi @ChengJiacheng , were you able to add adapter to t5? and I have a question, what task were you trying to do? a summarisation one, is it?
