### ISSUE TITLE
Quick Start Adapter was not found

### ISSUE THREAD

**Issue by Asdf11x** [Adapter-Hub/adapter-transformers#43]
# 🐛 Bug
Hi, I tried to run the Quickstart Tutorial [here](https://docs.adapterhub.ml/quickstart.html#introduction), so Im using that exact code. When loading the adapter with `model.load_adapter('sst')` Im getting an error mentioned below. Using "sst-2" instead of "sst" returns another warning?

## Information

Model I am using (Bert, XLNet ...):

Language I am using the model on (English, Chinese ...):

Adapter setup I am using (if any):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Run code from [here ](https://docs.adapterhub.ml/quickstart.html#introduction)
2.
3.

Using
```
# load pre-trained task adapter from Adapter Hub
# with with_head=True given, we also load a pre-trained classification head for this task
model.load_adapter('sst', config='pfeiffer', with_head=True)

# activate the adapter we just loaded, so that it is used in every forward pass
model.set_active_adapters('sst')
```
Returns
```
    raise EnvironmentError("No adapter with name '{}' was found in the adapter index.".format(specifier))
OSError: No adapter with name 'sst' was found in the adapter index.
```
Using:
```
# load pre-trained task adapter from Adapter Hub
# with with_head=True given, we also load a pre-trained classification head for this task
model.load_adapter('sst-2', config='pfeiffer', with_head=True)

# activate the adapter we just loaded, so that it is used in every forward pass
model.set_active_adapters('sst-2')
```
Returns 
```
INFO:transformers.adapter_bert:No prediction head for task_name 'sst-2' available.
WARNING:transformers.adapter_bert:No prediction head is used.
```

## Environment info

     
- `transformers` version: 2.11.0
- Platform: Linux-4.15.0-108-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: using quickstart tutorial

**Comment by JoPfeiff** [comment]
hey Asdf11x, looks like we forgot to update that, thanks for pointing that out!
You can select the sst-2 adapter with the adapter architecture and for the model you are using here:
https://adapterhub.ml/explore/sentiment/sst-2/
If you for example want to use the `pfeiffer` architecture for `bert-base-uncased` model this one would be the correct adapter:
https://adapterhub.ml/adapters/ukp/bert-base-uncased-sst_pfeiffer/
as mentioned on that page you would need to load it with the following code:
```
model = AutoModel.from_pretrained("bert-base-uncased")
config = AdapterConfig.load("pfeiffer")
model.load_adapter("sentiment/sst-2@ukp", "text_task", config=config)
```

**Comment by JoPfeiff** [comment]
A colab was already created for this:
https://colab.research.google.com/drive/1iEymIGmkX9_EjirgQpcKoVc-0wuv-DXN?usp=sharing
(check out the blog post: https://medium.com/towards-artificial-intelligence/nlp-news-cypher-07-19-20-75c1a3f7f57b)
