### ISSUE TITLE
How to train parallel adapters?

### ISSUE THREAD

**Issue by sallymoon10** [adapter-hub/adapter-transformers#463]
**Could you confirm if parallel training for adapters is possible or not with the latest version? 

If parallel training is not possible, what do you suggest I should do? Do I need to override a specific class / method in the package?
If parallel training is possible, would the following be the correct way to set it up?**

```
self.adapter_model = AutoModelWithHeads.from_pretrained("bert-base-uncased")

self.adapter_model.add_adapter('task1')
self.adapter_model.add_classification_head('task1', num_labels=len(self.id_to_task1), id2label=self.id_to_task1)
self.adapter_model.train_adapter("task1")  

self.adapter_model.add_adapter('task2')
self.adapter_model.add_classification_head('task2', num_labels=len(self.id_to_task2), id2label=self.id_to_task2)
self.adapter_model.train_adapter("task2")  

self.adapter_model.add_adapter('task3')
self.adapter_model.add_classification_head('task3', num_labels=len(self.id_to_task3), id2label=self.id_to_task3)
self.adapter_model.train_adapter("task3")  

# load parallel adapters
self.adapter_model.set_active_adapters(ac.Parallel("task1", "task2", "task3"))
```

- The notebook suggests that is is possible (https://github.com/adapter-hub/adapter-transformers/blob/master/notebooks/Parallel_Adapter_Inference.ipynb)
- The documentation suggests that is it not (https://docs.adapterhub.ml/adapter_composition.html)

Thanks for your help!

**Comment by hSterz** [comment]
Hey @sallymoon10, you can train parallel adapters. We will update the documentation on parallel compositions. To train a parallel composition you need a slightly different code to set it up: 
```
self.adapter_model.add_adapter('task1')
self.adapter_model.add_classification_head('task1', num_labels=len(self.id_to_task1), id2label=self.id_to_task1)

self.adapter_model.add_adapter('task2')
self.adapter_model.add_classification_head('task2', num_labels=len(self.id_to_task2), id2label=self.id_to_task2)

model.train_adapter(Parallel("task1", "task2"))
```

**Comment by sallymoon10** [comment]
Thanks for the help, seems to be working!

Just FYI for others, it seems like you also need to run the following to get the code running: 

```
self.adapter_model.set_active_adapters(ac.Parallel("task1", "task2", "task_3"))
```
