### ISSUE TITLE
AdapterTrainer requires <model> even if <model_init> was provided  

### ISSUE THREAD

**Issue by bartoszpawlowicz** [adapter-hub/adapter-transformers#481]
## Environment info

- `adapter-transformers` version: 3.1.0

## To reproduce

1. Create a <model_init> function to be used in hyperparameter tuning
2. Pass a <model_init> function to AdapterTrainer at its init without passing a model 

trainer = AdapterTrainer(
      model_init=model_init,
     # model=model,  # THIS SHOULD NOT BE REQUIRED IF <model_init> is provided
     args=training_arguments,
     train_dataset=train_dataset,
     eval_dataset=eval_dataset,
)

Error that I get:
AttributeError: 'NoneType' has no attribute 'active adapters'

The same code would work with standard HF transformers, with adapter-transformers it does not work.

I know that there is a workaround - just passing a mockup model that will never be used during hyperparameter search but this is not how the Library should behave. Maybe a simple if statement (if self.model and not self.model_init) before checking model properties is enought but maybe deeper check is required.

## Expected behavior

The same as with original HF Trainer - it should accept <model> OR <model_init> at the init phase

**Comment by bartoszpawlowicz** [comment]
any idea when the official release with this bug fix will be published? I see thats it is already merged to master but last release is from September...

**Comment by calpt** [comment]
@bartoszpawlowicz We're currently in the final preparations for the next release. Should be available some time in the next week.
