### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by fzalkow** [adapter-hub/adapter-transformers#509]
Hi,

The readme file specifies "Python 3.7+" as a requirement, which I understand as ">=3.7". However, the assignment operator `:=` is used in the file [`adapters/utils.py`](https://github.com/adapter-hub/adapter-transformers/blob/master/src/transformers/adapters/utils.py#L411), which is not allowed until Python 3.8.

Thanks for the great work with adapter-transformers!

**Comment by lenglaender** [comment]
@fzalkow from now on we will officially only support python3.8+ as python3.7 is only supported until June this year. Nevertheless, the master branch should currently be fully functional with python3.7, but we cannot say how long this will be the case.

Thanks for letting us know that adapter-transformers no longer worked with Python 3.7!
