### ISSUE TITLE
The documentation is confusing me about active_adapters

### ISSUE THREAD

**Issue by felixgaschi** [adapter-hub/adapter-transformers#517]
## Environment info

     
- `adapter-transformers` version: 3.2.0
- Platform: N/A
- Python version: N/A
- PyTorch version (GPU?): N/A

## Details

The documentation is confusing me about how the property `active_adapters` really works:

It [here](https://docs.adapterhub.ml/adapter_composition.html#adapter-activation) that: "`active_adapters` defines which of the available adapters are used in each **forward** and **backward** pass"

This could suggests that putting an adapter in `active_adapters` it would make it trainable. But from my understanding, it doesn't, since you also need to use `model.train_adapter` to make it trainable, as showcased in the [MAD-X example](https://colab.research.google.com/github/Adapter-Hub/adapter-transformers/blob/master/notebooks/04_Cross_Lingual_Transfer.ipynb), and explained in the answer to issue #318.

Could you confirm that adapters in `active_adapters` are not necessarily trainable ? 

Also as a side question (I could open another issue if needed): is the context manager `AdapterSetup` strictly equivalent putting adapters in `active_adapters` or does it make them trainable ?

**Comment by hSterz** [comment]
Hey @felixgaschi , you are right`active_adapters` are not necessarily trainable. `active_adapters`are just the adapters used in the forward pass. Hence, they are also used in the backward pass. But to ensure that the adapter weights are updated and the remaining weights are frozen you need to call the `train_adapter` method, which sets the `requires_grad` for the weights. 
The `AdapterSetup` is equivalent to setting the  `active_adapters`.

**Comment by felixgaschi** [comment]
Thank you for the clarification @hSterz ! I have an additional question: does `train_adapter` applied to a given adapter freezes all other existing adapters as well as the pretrained model or do I have to manually freeze the weights of any adapter I might have trained before that?

Like if I do something like the following, "adapter_1" is frozen when training the second one, isn't it ?

```{python}
# create a model with registered adapter_1 and adapter_2

model.train_adapter(["adapter_1"])

# Train the first adapter 

model.train_adapter(["adapter_2"])

with AdapterSetup(Stack("adapter_1", "adapter_")):
    # Train the second adapter
```

**Comment by calpt** [comment]
@felixgaschi Yes, your assumption is correct. `train_adapter()` will freeze all weights of the base model + all weights of other adapters except for the adapter(s) passed as arguments to the method.
