### ISSUE TITLE
Can I add adapters into custom PyTorch transformer layer?

### ISSUE THREAD

**Issue by kaneyxx** [adapter-hub/adapter-transformers#522]
## Environment info
- `adapter-transformers` version: 3.2.0
- Python version: 3.9.16
- Platform: macOS-10.16-x86_64-i386-64bit- Python version:
- PyTorch version (GPU?): 2.0.0 (False)

## Details
Hello, thanks for the awesome hub at first, I've learned a lot here. Really appreciate it! I'm working at a project and design an architecture by myself. (Basically that are several PyTorch building transformer encoder layers. Not based on the original transformers library) Is it possible that I can plugin the adapter into the architecture by calling function from this hub?

Thanks for kindly answering :)

**Comment by hSterz** [comment]
Hey @kaneyxx , it is great to hear about your excitement about our hub. Yes, you can add adapters to your custom model. But unfortunately, this will need a few changes. It is like to adding support to a new model (see the [docs](https://docs.adapterhub.ml/contributing/adding_adapters_to_a_model.html)). Of course, you can skip the steps that are not relevant to your use case. In general, I would recommend having a look at the diff between our modeling_bert.py file and the huggingface file in v.4.26.1 (or the modeling_X.py file of the model most similar to your architecture).
If yo run into any problems don't hesitate to write again.

**Comment by kaneyxx** [comment]
Hi @hSterz , Thanks for answering and also thanks for the hint. I will take a look at those document and implementation file. Thanks for the help :)
