### ISSUE TITLE
How to add other information into the adapters?

### ISSUE THREAD

**Issue by kaneyxx** [adapter-hub/adapter-transformers#533]
## Details
Hello, I'm trying the awesome adapters. Here's my question: after initiating the model and add the adapters. If I have another input want to concatenate specific layer output and then input adapter. Is it possible to modify the forward path?

**Comment by hSterz** [comment]
Hey @kaneyxx, unfortunately modifying the forward path is not supported out of the box. Depending on where you want the changes and what changes they are you can use Python hooks or you can manipulate the adapter transformers implementation at the necessary points. Maybe you can give a bit more detail on the setup you are trying to achieve.

**Comment by hSterz** [comment]
Depending on what you want to insert, it should be possible using pytorch hooks. You can add functionality before the adapter by adding a hook before the forward call. That way your added info is executed before the adapters forward method. This is a [blog post](https://medium.com/analytics-vidhya/pytorch-hooks-5909c7636fb) on hooks that might help you. 
Let me know whether this works for your use case.

**Comment by kaneyxx** [comment]
Looks great! Thanks for help.
I'll try it in recent days and let you know if this works for my case.

**Comment by kaneyxx** [comment]
@hSterz I already tried pre-hook trick for my project. It works very well. Thanks for you help and information. I will close this comment with completed.
