### ISSUE TITLE
AttributeError: 'BartConfig' object has no attribute '_to_dict_new'`

### ISSUE THREAD

**Issue by vatsal-kr** [adapter-hub/adapter-transformers#534]
While using adapter-transformers==3.0.0, I get the following error on running my code

```
    config = AdapterConfig.load("houlsby", non_linearity="swish", reduction_factor=2, load_from_cache=False)
    bart_model.load_adapter("sum/cnn_dailymail@ukp", config=config)
    bart_model.train_adapter("summarization")
    
    bart_model.resize_token_embeddings(len(tokenizer))
    model = LitModel(learning_rate = 2e-5,
                     tokenizer = tokenizer,
                     model = bart_model,
                     args=args)
    trainer = pl.Trainer(accelerator = 'gpu',
                         devices = args.devices_list,
                         max_epochs = args.num_epochs,
                         auto_lr_find = False,
                         precision = 16)
    trainer.fit(model, data)
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vave/anaconda3/envs/adapters/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/vave/anaconda3/envs/adapters/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/vave/anaconda3/envs/adapters/lib/python3.8/site-packages/transformers/configuration_utils.py", line 252, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'BartConfig' object has no attribute '_to_dict_new'
```

This issue sometimes fixes itself by deleting the environment, or by reinstalling adapter-transformers, but shows up again after running the script once.

PS: For my use case, I need to break down the model into the encoder and decoder because there is some processing to be done on the encoder outputs. I am using v 3.0.0 because with the latest version, I get an error: `NoneType has no attribute output_adapter_gating_scores`, on calling the `self.encoder(input_ids, attention_mask)`

**Comment by mhn226** [comment]
Hi @vatsal-kr , I have the same "NoneType has no attribute output_adapter_gating_scores" when calling self.encoder() method. I don't know if you have an idea of what happened and how to fix? Thanks!

**Comment by vatsal-kr** [comment]
Hey @mhn226,
I installed adapter-transformers v3.0.0 and made the changes as per #https://github.com/adapter-hub/adapter-transformers/pull/406/commits/2e5973f68837e04396e4400f741b4e92d3f4e1a8. This solved the issue for me
