### ISSUE TITLE
 'RobertaModel' object has no attribute 'add_adapter'? 

### ISSUE THREAD

**Issue by songmh99** [adapter-hub/adapter-transformers#536]
## Environment info

- `transformers` version: 4.28.1
- Platform: Windows-10
- Python version: 3.9.16
- Huggingface_hub version: 0.13.4
- Safetensors version: not installed
- PyTorch version (GPU?): 1.13.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## Details
```python
from transformers import RobertaConfig
from transformers.adapters import RobertaAdapterModel

config = RobertaConfig.from_pretrained('roberta-base',num_labels=2)
model = RobertaAdapterModel.from_pretrained('roberta-base')

model.add_adapter('rotten_tomatoes')
``` 

I got the error: 

   1263     if name in modules:
   1264         return modules[name]
-> 1265 raise AttributeError("'{}' object has no attribute '{}'".format(
   1266     type(self).__name__, name))

AttributeError: 'RobertaModel' object has no attribute 'add_adapter'? 

Why is there no attribute 'add_adapter'? How can I solve this problem?

**Comment by lpq29743** [comment]
May you please provide the final solution to your issue?
