### ISSUE TITLE
Does the currently implementation support adding adapters just to some layers?

### ISSUE THREAD

**Issue by ajesujoba** [adapter-hub/adapter-transformers#547]
Is it possible to add adapters to some selected layers without adding them to all the layers using the currently code base? If no, any clues on the most appropriate to do this? Can I use it with the run_mlm.py script?

I noticed there is the leave_out parameter, I tried it 

```
from transformers import AutoAdapterModel, AdapterConfig
model = AutoAdapterModel.from_pretrained("xlm-roberta-base")
config = AdapterConfig.load("pfeiffer", non_linearity="relu", reduction_factor=2, leave_out = list(range(5)))
model.load_adapter("en/wiki@ukp", config=config)
```

But the adapters were still added

**Comment by calpt** [comment]
Hey, this depends a bit on whether you'd want to a) add **randomly initialized** adapters or b) load **pre-trained** adapters.

a) To add randomly initialized adapter for training (via `add_adapter()`), the way of using `leave_out` shown in your code snippet should work, i.e.:

```python
config = AdapterConfig.load("pfeiffer", non_linearity="relu", reduction_factor=2, leave_out = list(range(5)))
model.load_adapter("en/wiki@ukp", config=config)
```

This will add randomly initialized adapter modules to all layers with ids >= 5.

b) From your snippet, it seems you'd like to load a pre-trained adapter via `load_adapter()`. As each pre-trained adapter is trained with a specific config, changing the `leave_out` parameter within the config won't affect the loaded adapter. To drop certain adapter layers from the pre-trained adapter for inference, you can pass `leave_out` to the `load_adapter()` method, i.e.:

```python
config = AdapterConfig.load("pfeiffer", non_linearity="relu", reduction_factor=2)
model.load_adapter("en/wiki@ukp", config=config, leave_out = list(range(5)))
```

Hope this helps!

**Comment by ajesujoba** [comment]
It helps. Thanks!
