### ISSUE TITLE
Combine Multi PEFT method

### ISSUE THREAD

**Issue by Iambestfeed** [adapter-hub/adapter-transformers#560]
**In your opinion, is it possible to combine Parameter-Efficient Fine-Tuning methods like Lora, Prefix Tuning together?**
I found [Mix-and-Match Adapter](https://docs.adapterhub.ml/method_combinations.html#mix-and-match-adapters) where I can combine Prefix Tuning and parallel bottleneck adapters but I wonder if it's still possible to incorporate Lora in anymore? 

I don't have much experience so can someone suggest me some tutorials so I can learn how to experiment with these problems?

**Comment by adapter-hub-bert** [comment]
This issue was closed because it was stale for 14 days without any activity.
