### ISSUE TITLE
Work with Pytorch Lightning

### ISSUE THREAD

**Issue by dyxohjl666** [adapter-hub/adapter-transformers#562]
I' m working on using adapters to learn domain specific knowledge. Since my previous work is based on Pytorch Lightning, I tried to train adapters with it too. However, the document says that " `AdapterTrainer` is only intended for training adapters. The `Trainer` class should still be used to fully fine-tune models. ". I thought it means if I use `Trainer`, all the parameters will be finetuned. 

But Pytorch Lightning's Trainer doesn't have an "Adapter" version. Is it possible I use AdapterHub with Pytorch Lightning?

**Comment by armin-zd** [comment]
You can use the lightning `Trainer` as usual with your adapter model. Just do `model.train_adapter(adapter_id)` before passing it to `trainer.fit`, which disables training of all weights outside the task adapter.
