### ISSUE TITLE
Supporting DistilBERT model

### ISSUE THREAD

**Issue by z-lai** [Adapter-Hub/adapter-transformers#58]
Hi,

I really like this project and I am wondering if the adapter-transformers could support DistilBERT model,
since I have following errors when I trained an adapter for my own DistilBERT:

### Training:  https://colab.research.google.com/github/Adapter-Hub/website/blob/master/app/static/notebooks/Adapter_Quickstart_Inference.ipynb#scrollTo=2xwdA1sz7eZO
```
model_name = "bandainamco-mirai/distilbert-base-japanese"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelWithHeads.from_pretrained(model_name)
model.add_adapter("yahoo_movie_reviews", AdapterType.text_task)
model.train_adapter(["yahoo_movie_reviews"])
```
Then I got:
```
'ValueError: Unrecognized configuration class  for this kind of AutoModel: AutoModelWithHeads.
Model type should be one of XLMRobertaConfig, RobertaConfig, BertConfig.
```

### Inference: https://colab.research.google.com/github/Adapter-Hub/website/blob/master/app/static/notebooks/Adapter_Quickstart_Inference.ipynb#scrollTo=2xwdA1sz7eZO
```
model = AutoModelForSequenceClassification.from_pretrained("bandainamco-mirai/distilbert-base-japanese")
tokenizer = AutoTokenizer.from_pretrained("bandainamco-mirai/distilbert-base-japanese")
model.load_adapter("adapter/yahoo_movie_reviews")
```
Then I got:
```
AttributeError: 'DistilBertForSequenceClassification' object has no attribute 'load_adapter'
```
I wonder if it is possible to train an adapter for DistilBERT by changing part of exist codes.

Thanks for any insights on that.

**Comment by calpt** [comment]
Hi @z-lai,

We currently have adapter integrations for Bert, Roberta & XLM-Roberta, so DistilBERT is _not_ supported _yet_.

Adding support for new models requires implementing integration of adapter modules into the respective model class. All model classes with adapter integration implement [a common base class](https://docs.adapterhub.ml/classes/model_mixins.html) and have some modifications in the module classes ([diff between our and HuggingFace's Bert code as an example](https://github.com/calpt/adapter-transformers/compare/v2.11.0...Adapter-Hub:master#diff-909b7609d41ab4e784249a7d6dae6a2c)). The changes to the DistilBERT model class would be non-trivial, but shouldn't be overly complex.
