### ISSUE TITLE
Supporting GPT-2 model

### ISSUE THREAD

**Issue by lutz-100worte** [Adapter-Hub/adapter-transformers#62]
# 🚀 Feature request

Similar to #58 it would be nice to have support for :unicorn: GPT-2.

**Comment by calpt** [comment]
To give an answer here on GitHub too: This was also [asked and answered](https://twitter.com/GeileHirnbude/status/1308759567833145344) on Twitter. GPT-2 support is on our plan.

**Comment by li3cmz** [comment]
> To give an answer here on GitHub too: This was also [asked and answered](https://twitter.com/GeileHirnbude/status/1308759567833145344) on Twitter. GPT-2 support is on our plan.

Hi, I wanna try to implement the adapter for GPT-2. And I wonder if the changes for supporting  GPT-2 are similar to those for [DistilBERT](https://github.com/Adapter-Hub/adapter-transformers/issues/58#issuecomment-694743554)?

**Comment by hSterz** [comment]
Hi, I am currently working on implementing adapters for GPT-2.

**Comment by li3cmz** [comment]
> Hi, I am currently working on implementing adapters for GPT-2.

Could I ask about how long will it take?

**Comment by li3cmz** [comment]
> Hi, I am currently working on implementing adapters for GPT-2.

Could I ask how long will it probably take?

**Comment by hSterz** [comment]
I think this should be finished in the beginning of january.

**Comment by lutz-100worte** [comment]
I appreciate your work on this, @hSterz ! Does [this merged pull request](https://github.com/Adapter-Hub/adapter-transformers/pull/123) mean GPT-2 is supported now? :heart_eyes:

**Comment by hSterz** [comment]
Yes, the implementation on the v2 branch supports adapters for GPT-2 models.

**Comment by calpt** [comment]
Closing as GPT-2 is now officially released with v2.
