### ISSUE TITLE
Hinglish Sentiment Adapter

### ISSUE THREAD

**Issue by NirantK** [Adapter-Hub/adapter-transformers#73]
# 🌟 New Adapter setup

## Model and Data Description

Hinglish: Romanized version of Hindi, and is immensely popular in India, where Hindi is spoken by millions of people but typed quite often in Roman script

Dataset: [SemEval 2020 Task 9 Sentiment Analysis](https://ritual-uh.github.io/sentimix2020/hinglish_res): 3 classes, +ve, -ve and neutral

## Open source status

* [x] Code Implementation for the Adapter: https://colab.research.google.com/drive/19lofRd9n142xJCtUteZb5L_r7spGcGLL?usp=sharing 
* [x] Past Work: [Accepted Paper](https://arxiv.org/abs/2008.09820), [Code and Model Weights](https://github.com/NirantK/Hinglish/)
* [x] Who are the authors: @NirantK and @meghanabhange

## What I need help with

* [x] Because there were no examples other than Glue Datasets, I ended up implementing a new `HinglishDataset` class and [other skeleton code](https://colab.research.google.com/drive/19lofRd9n142xJCtUteZb5L_r7spGcGLL?usp=sharing) -- I'd appreciate a review if I got something wrong

## Next Steps

If all is well in the code above, I'd like to continue along and contribute an adapter for Hinglish under the Sentiment task.

**Comment by calpt** [comment]
Had a quick look at your training setup and code, seems to look good to me. The adapter setup setup seems to be correct and the rest of the data preprocessing and training should be identical to a Huggingface transformers setup. I didn't do a full training run, so maybe the training results tell more about if there's something wrong.

Would be great to have this as a new task with adapters [in the Hub](https://github.com/Adapter-Hub/Hub)! If you need any further help beyond what's already described [in the documentation](https://docs.adapterhub.ml/contributing.html), just let me know :)

**Comment by NirantK** [comment]
Thanks for the encouragement @calpt! Will start working on this today after work/during work-breaks :)

**Comment by NirantK** [comment]
I ran this command
```bash
$ python scripts/check.py -f adapters/nirantk/bert-base-multilingual-uncased-hinglish-sentiment.yaml                                        
```

This is the output:
```
----- Checking format of adapters/nirantk/bert-base-multilingual-uncased-hinglish-sentiment.yaml -----
PASSED: adapters/nirantk/bert-base-multilingual-uncased-hinglish-sentiment.yaml.

----- Checking download of adapters/nirantk/bert-base-multilingual-uncased-hinglish-sentiment.yaml -----
VIOLATION: [OSError]: Unable to load file from None. The file might be unavailable.
FAILED: adapters/nirantk/bert-base-multilingual-uncased-hinglish-sentiment.yaml!
```

YAML is here: 
https://github.com/NirantK/Hub/blob/add-Hinglish/adapters/nirantk/bert-base-multilingual-uncased-hinglish-sentiment.yaml

The adapter files are here: https://github.com/NirantK/Hinglish/releases/download/adapter.v.1/hinglish-bert-base-multilingual-uncased-20201019T062947Z-001.zip

What I expect: The download URL seems to work both via `wget` and `urllib`, that file should have been downloaded and found. 

What is happening: It is unable to find the file path or URL. 

Can you please take a quick look at what have I been doing wrong?

**Comment by calpt** [comment]
Just made a quick check and it looks like you found a limitation of GitHub Releases. GitHub's AWS service doesn't allow HTTP HEAD requests (returning HTTP 403), but these are used for our/ Huggingface's file caching functionality. For testing purposes, I downloaded your zip folder manually and uploaded it to my own server. Everything ran successfully.

We'll see if we can find a workaround for this, as GitHub Releases might be a popular hosting location. Until then, maybe you might just use another hosting location instead (e.g. uploading as part of a GitHub repository [seems to work](https://github.com/Adapter-Hub/Hub/blob/master/adapters/mapmeld/bert-base-arabert-ar-dialect.yaml#L35)). If you wish, I can also upload your adapter to our Lab's file server (where all our adapters are hosted too).

**Comment by NirantK** [comment]
Thanks @calpt. I can confirm that this is indeed the case. 

Please upload to your University server for now and share a link? Thank you so much for offering!
I'll setup the parallel repo in meantime so that it's faster when/if I want to add more adapters around similar tasks.

**Comment by calpt** [comment]
Here you go: https://public.ukp.informatik.tu-darmstadt.de/AdapterHub/contrib/nirantk/hinglish-bert-base-multilingual-uncased-20201019T062947Z-001.zip

**Comment by NirantK** [comment]
Done! The checks cleared now.

Raised a PR: https://github.com/Adapter-Hub/Hub/pull/14

**Comment by NirantK** [comment]
Woohoo 🎉 

This is done with Adapter-Hub/Hub#14


Thanks a ton @calpt for guiding throughout this :)
