### ISSUE TITLE
Examples for zero-shot cross-lingual transfer for Classification

### ISSUE THREAD

**Issue by PhungVanDuy** [Adapter-Hub/adapter-transformers#76]
### 🌟 New adapter setup

Add code examples for zero-shot cross-lingual transfer like classification problem.

### Motivation

As the description at [Adapter documentation](https://docs.adapterhub.ml/adapters.html), I understand that the adapter can be performed zero-shot cross-lingual transfer, so I am facing the problem that I want to build a classification model will be train on English and test on another language like Chinese, Spanish,.. so can you add an example to use Adapter for this setting. 

I already go through available examples but I still did not clarify how to use it, please let me know if I missed something.

Thank you so much

**Comment by calpt** [comment]
Hi @PhungVanDuy (and sorry for the delayed answer),

Cross-lingual task transfer in AdapterHub is realized as described in the [MAD-X paper](https://arxiv.org/pdf/2005.00052.pdf). Basically, this involves 3 steps:

1. Language adapters (`AdapterType.text_lang`): You can either [train language adapters](https://docs.adapterhub.ml/training.html#train-a-language-adapter) for the source and target language on a language modeling task yourself or [use pre-trained language adapters from the Hub](https://adapterhub.ml/explore/text_lang/). E.g., a pre-trained adapter could be loaded using:

```python
config = AdapterConfig.load("pfeiffer", non_linearity="relu", reduction_factor=2)
model.load_adapter("<lang_adapter>", "text_lang", config=config)
```

2. [Training a task adapter](https://docs.adapterhub.ml/training.html#train-a-task-adapter) (`AdapterType.text_task`) for the classification task stacked upon a language adapter: We add a new task adapter on top of the language adapter and train only the task adapter on the target task.
```python
model.add_adapter("<task_name>", AdapterType.text_task)
model.set_active_adapters([
    ["<source_lang_adapter>"],
    ["<task_name>"]
))
model.train_adapter(["<task_name>"])
```
3. Replace source language with target language for zero-shot inference:

```python
model.load_adapter("<target_lang_adapter>", AdapterType.text_lang)
model.set_active_adapters([
    ["<target_lang_adapter>"],
    ["<task_name>"]
))
```

Unfortunately, we don't have a full example with explanations for this yet, but there will be a Colab notebook with an example for cross-lingual transfer soon. Hope these snippets still give you a general idea how it works.
