### ISSUE TITLE
What is the best way to use this repo in conjunction of AllenNLP?

### ISSUE THREAD

**Issue by arkgithubforyou** [Adapter-Hub/adapter-transformers#78]
Hi,

So AllenNLP has already wrapped many transformer classes from the original transformers library, which uses many same names as adapter-transformers (since the latter was forked from the former).

**Comment by calpt** [comment]
Hi @arkgithubforyou,

I must say that I'm not particularly familiar with AllenNLP. In general, you should be able to use adapter-transformers as a drop-in replacement for HuggingFace transformers as we kept the same namespace and model classes. I assume there isn't any dedicated adapter integration for AllenNLP, but if you face any issues when using this library together with it, we can try to improve that as far as it's possible from our side.
