### ISSUE TITLE
Integrate AdapterDrop

### ISSUE THREAD

**Issue by arueckle** [Adapter-Hub/adapter-transformers#84]
# 🚀 Feature request

Add our internal implementation of AdapterDrop to the AdapterHub repository.
https://arxiv.org/abs/2010.11918

This consists of several smaller features, which I'll add later to this feature request.

**Comment by AmirAktify** [comment]
Just to vote here, that I'm following this and will be using it for our company's releases this summer.

**Comment by arueckle** [comment]
Great to know! We are currently integrating the required changes into our upcoming release (v2 of AdapterHub). It will be available in a few weeks.

**Comment by calpt** [comment]
Closing with release of v2.
