### ISSUE TITLE
moving computation inside get_adapter_preparams to the adapter forward 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [Adapter-Hub/adapter-transformers#94]
Hi
I see currently you have implemented part of computation of adapter layers inside get_adapter_preparams 
see https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_bert.py line 107, this is confusing and to me the best is putting all computation in one place, this is inside Adapter class https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_modeling.py, line 43 to allow track the method easier.
thanks.
Best
Rabeeh

**Comment by rabeehkarimimahabadi** [comment]
My second suggestion is to choose a "coherent" names, looking into adapter_bert you pass add_layer_norm_after=adapter_config["ln_after"] 
to make code easier to read, it would be better to call ln_after from beginning in the config files, as add_layer_norm_after, specially ln by itself can be confusing and is better to choose a name which is easily understandable. thanks

**Comment by calpt** [comment]
In general, I agree that not all of the configuration options are self-descriptive and that the implementation part is not particularly well-documented. So thanks for sharing your improvement suggestions from working with our code, we'll try to make it more understandable and some more explanations. For the moment, [this figure from our documentation](https://docs.adapterhub.ml/_images/architecture.png) might help in understanding as it maps the config keys to a visual representation. Some comments to your points:

> I see currently you have implemented part of computation of adapter layers inside get_adapter_preparams
see https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_bert.py line 107, this is confusing and to me the best is putting all computation in one place, this is inside Adapter class https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_modeling.py, line 43 to allow track the method easier.

The reasoning behind this split is that that the operations in `get_adapter_preparams()` are technically not part of the actual adapter module and therefore not implemented in `adapter_modeling.py`. See the linked figure for context (e.g. "ln_before" is part of the adapter (pink box) and thus in `adapter_modeling.py` whereas `original_ln_before` is not and thus in `get_adapter_preparams()`).

> looking into adapter_bert you pass add_layer_norm_after=adapter_config["ln_after"]
to make code easier to read, it would be better to call ln_after from beginning in the config files, as add_layer_norm_after, specially ln by itself can be confusing and is better to choose a name which is easily understandable.

Agree.

> you have defined both residual_before_ln and adapter_residual_before_ln, could you explain the differences?

See the linked figure.

> I am not getting why you apply the same operation with different condition could you express on it?

There should be a line

```
if adapter_config["original_ln_before"]:
    hidden_states = self.layer_norm(hidden_states + input_tensor)
```

between the lines you posted. This line applies a layer norm, the two lines you posted determine whether the residual inputs should be taken from before the layer norm is applied (first statement) or after (second statement). Note that this doesn't make a difference if `original_ln_before` is `False` (as in Houlsby).

Hope this clears things up a bit!

**Comment by rabeehkarimimahabadi** [comment]
thank you for the helpful explanations.
