### ISSUE TITLE
possible bug with adapter_bert implementation 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [Adapter-Hub/adapter-transformers#95]
Hi 
Looking into adapter_bert inside  "adapter_stack_layer" function, you first call self.get_adapter_preparams, there for case of Hausbly adapter config, you change the residual to hidden_state, after this fucntion call in line 178, both hidden_states and residual are the same value of hidden_states, then they feed into the  adapter_layer(), is this the correct behaviour expected to feed the same input to this layer? thanks

**Comment by calpt** [comment]
Hi,

If I understood you correctly then yes, this is intended. In Houlsby architecture, the hidden state directly before the input to the adapter module is used for the residual connection. Thus, this hidden state is passed to the adapter module twice, once to be passed through the adapter's down- and up-projection and once for the residual afterwards.

Maybe [this figure](https://docs.adapterhub.ml/_images/architecture.png) from our documentation helps to make this a bit more clear, it maps the keys of the adapter config to the visualization of a Transformer module.

**Comment by rabeehkarimimahabadi** [comment]
thank you for the response.
