### ISSUE TITLE
the reason for add_classification_head

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [Adapter-Hub/adapter-transformers#96]
Hi
I read the description here https://docs.adapterhub.ml/prediction_heads.html 
I am not getting why adding add_classification_head is needed? could you give more details on why one needs to introduce it and how it works? thanks.

**Comment by calpt** [comment]
The `add_classification_head()` method is our implementation of adding a final task-specific prediction head on top of the last layer of the Transformer model, in this case a simple FF layer to map the final hidden state to one of n classes in a sequence classification problem. This is specific to our `AutoModelWithHeads` class to allow flexibly adding and switching between multiple prediction heads. Therefore, this is _not_ needed in case you don't need this kind of final prediction head layer or provide your own.

**Comment by rabeehkarimimahabadi** [comment]
thank you
