### ISSUE TITLE
is pretraining of adapter layers is necessary for performance? 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [Adapter-Hub/adapter-transformers#97]
Hi
I have added adapter layers to my custom model and currently getting very low performance, could you tell me if adapter layers needs special pretraining and how I can do this pretraining? I am defining them from scratch and freeze the model and then train the adapters. thanks.

**Comment by arueckle** [comment]
We have some experiments with pre-trained adapters in the [AdapterDrop paper](https://arxiv.org/pdf/2010.11918.pdf) (figure 6). It turns out that random initialization is pretty good. It seems like pre-training is not needed
