### ISSUE TITLE
layernorm should be set to trainable or not ? 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [Adapter-Hub/adapter-transformers#98]
Hi,
I see in some implementations they set layer_norm as require_grad=True, could you tell me if all layer norms of the model needs to be set to require_grad=True, or only the ones inside adapter layer needs this condition?
thanks.

**Comment by arueckle** [comment]
See figure 3 in the adapterhub paper, everything outside the pink box is fixed/frozen during adapter training

**Comment by rabeehkarimimahabadi** [comment]
Hi Andreas
but looking into their original paper implementation, this is not frozen,
also classifier is not. Could you confirm which one is correct?
thanks
